### ISSUE TITLE
why the offline of datapartion does not guarantee more than half of the number of copies？

### ISSUE THREAD

**Issue by jadewang198510** [chubaofs/chubaofs#1010]
In the datapartion/metapartion offline  process, the processing is different, why the offline of datapartion does not guarantee more than half of the number of copies？ we know ,  datapartion also can in  the raft proccessing, why ？
1.metapartion offline.
![image](https://user-images.githubusercontent.com/71998751/98497351-adadbc00-227e-11eb-838d-7679cd11ca78.png)
2.datapartion offline.
![image](https://user-images.githubusercontent.com/71998751/98497385-cddd7b00-227e-11eb-80dc-e94d4743572f.png)

**Comment by mervinkid** [comment]
@jadewang198510 
Because if the number of surviving members is less than half, the `raft` cannot work properly.
