### ISSUE TITLE
build fails 'undefined reference to `dlopen''

### ISSUE THREAD

**Issue by dbpaul** [chubaofs/chubaofs#103]
I am trying to build it on ubuntu 16.04
git clone https://github.com/facebook/rocksdb.git
apt install libgflags-dev libsnappy-dev zlib1g-dev libbz2-dev  libzstd1-dev liblz4-dev
cd rocksdb && make clean && ROCKSDB_NO_FBCODE=1 make static_lib -j12 && make install

cd && export GOPATH=$HOME/go
go get github.com/chubaofs/chubaofs
cd ~/go/src/github.com/chubaofs/chubaofs/cmd && sh build.sh

 github.com/chubaofs/chubaofs/vendor/github.com/tiglabs/raft/proto
../vendor/github.com/tiglabs/raft/proto/codec.go:275: undefined: sort.Slice
 github.com/chubaofs/chubaofs/vendor/github.com/prometheus/common/expfmt
../vendor/github.com/prometheus/common/expfmt/text_create.go:456: undefined: bytes.ContainsAny
 github.com/chubaofs/chubaofs/vendor/github.com/tecbot/gorocksdb

//usr/local/lib/librocksdb.so: undefined reference to dlopen'
//usr/local/lib/librocksdb.so: undefined reference to dlclose'
//usr/local/lib/librocksdb.so: undefined reference to dlerror'
//usr/local/lib/librocksdb.so: undefined reference to dlsym'
collect2: error: ld returned 1 exit status

**Comment by awzhgw** [comment]
@dbpaul  you can use 
echo "deb http://deb.debian.org/debian stretch-backports main" >> /etc/apt/sources.list && \
        apt-get update && \
        apt-get -y install libz-dev libbz2-dev libsnappy-dev && \
        apt-get -y -t stretch-backports install librocksdb-dev
install rocksdb ,then build chubaofs

**Comment by awzhgw** [comment]
@dbpaul  you can use 
echo "deb http://deb.debian.org/debian stretch-backports main" >> /etc/apt/sources.list && \
        apt-get update && \
        apt-get -y install libz-dev libbz2-dev libsnappy-dev && \
        apt-get -y -t stretch-backports install librocksdb-dev
install rocksdb ,then build chubaofs

**Comment by awzhgw** [comment]
@dbpaul  please use rocksdb 5.9.2 build rocksdb

**Comment by dbpaul** [comment]
Thanks for your help,
first let me say I made it compile with adding
```
export LD_LIBRARY_PATH=/usr/local/lib:$LD_LIBRARY_PATH
CGO_CFLAGS="-I/usr/local/include" CGO_LDFLAGS="-L/usr/local/lib -lrocksdb -ldl" go build ........
```
to build.sh and upgrading GO to a version > 1.6

For your comment I tried
```
echo deb http://archive.ubuntu.com/ubuntu xenial-backports main restricted universe multiverse >> /etc/apt/sources.list
apt update && apt install libz-dev libbz2-dev libsnappy-dev && apt-get -y -t  xenial-backports install librocksdb-dev
```

I  don't really know what you mean by install rocksdb , an apt-get -y -t xenial-backports install rocksdb does not find rocksdb
I added 
export LD_LIBRARY_PATH=/usr/lib:$LD_LIBRARY_PATH
CGO_CFLAGS="-I/usr/include" go build .......
to build.sh, but building chubaofs still failed.
