### ISSUE TITLE
enhance: when we use fuse mount ,miss sk verify, it 's not safe 

### ISSUE THREAD

**Issue by seasan666** [chubaofs/chubaofs#1037]
when we use fuse ,may be the user has ak and sk, but sk not use for verify, when the user config miss sk, it aslo can mount successfull, it 's not safe for bussiness. it can enhance safe for mount ;
when we fuse mount, we need sk for verify ,only config sk is match user 's sk can sucessfull ,otherwise  it failed.

**Comment by mervinkid** [comment]
The use of secret key to verify when mounting is optional, it is out of the experimental stage. 
Access key+secret key is currently a required authentication method for S3 APIs. 
Using secret key as mount verification is not suitable for product design. 
I think we should design an independent key authentication method for mount.
