### ISSUE TITLE
Bug report：dataNode GetPreAllocSpaceExtentIDOnVerfiyFile function 

### ISSUE THREAD

**Issue by seasan666** [chubaofs/chubaofs#1046]
https://github.com/chubaofs/chubaofs/blob/5fa1f6995d8c0b5268ed61361ac9b95b01c3a90f/storage/persistence_crc.go#L68-L76

bug info as annotation

**Comment by mervinkid** [comment]
ACK

**Comment by mervinkid** [comment]
The pull request #1047 fixes this issue.
