### ISSUE TITLE
[已弃坑]删除DP数量过多卷，导致 CFS 集群雪崩

### ISSUE THREAD

**Issue by zcola** [chubaofs/chubaofs#1049]
**Describe the bug**
#1041 #1040 承接这两个问题，计划分批删除三个卷，合计 1W个 DP，11:20-11:40 删除了发现没反应，卷还在，可能是异步的，再后来，DN就开始陆续挂掉，最后只有一台 DN幸存，DN配置了挂掉自动拉起。

这卷都不在了，请问为什么过了十多分钟DN 还在尝试修复？而且卷得磁盘占用为0，因为上面的数据都迁走了，也就是我删除个卷我还得把自动修复关了，删除限速给开起来？
```
zcola@elk-chubao62-200:~$ du -sh  /disk6/datapartition_56143_128849018880/
428M	/disk6/datapartition_56143_128849018880/

[ERROR] data_partition_repair.go:149: buildDataPartitionRepairTask PartitionID(56143) on (10.90.141.222:17310) err([data_partition_repair.go 200] getRemoteExtentInfo DataPartition(56143) get host(10.90.141.222:17310) connect :: dial tcp 10.90.141.222:17310: connect: connection refused)
```
当时有问题的截图。

![image](https://user-images.githubusercontent.com/3234989/102181562-c6e10280-3ee5-11eb-8a04-01e7b286e3a5.png)

现在正常的截图
![image](https://user-images.githubusercontent.com/3234989/102181264-33a7cd00-3ee5-11eb-8616-6fb5f950f436.png)

**Comment by seasan666** [comment]
这个DP数量过多导致CBFS雪崩的问题，将在2.4 release版本修复，预计在4月底发布；
目前2.3以前的版本避规的方式，1个存储节节点，DP尽量不要超过3000个。暂时避规这个雪崩问题；后面升级到2.4版本后就没有这个问题

**Comment by jadewang198510** [comment]
fix by  #1124

**Comment by zcola** [comment]
确认，删掉了
