### ISSUE TITLE
In the datanode's repaire process, an extent will be repaired multiple times, and in the worst case, an extent will be repaired in parallel.

### ISSUE THREAD

**Issue by jadewang198510** [chubaofs/chubaofs#1050]
In the datanode's repaire process, an extent will be repaired multiple times, and in the worst case, an extent will be repaired in parallel.
step1.  The master node appends the extent to be repaired to the repaired queue once, the code is as follows:
![image](https://user-images.githubusercontent.com/71998751/102439525-6246b480-4059-11eb-9f94-000953f39f7e.png)

step2.  After the master node sends the task to the follower (notifyFollower), the follower re-appends the extent again, the code is as follows:
![image](https://user-images.githubusercontent.com/71998751/102439647-8f936280-4059-11eb-8255-5cdd2b82351c.png)

**Comment by jadewang198510** [comment]
After verification, the problem is confirmed to exist, and the extent may be repaired in parallel，debug log like this：
![image](https://user-images.githubusercontent.com/71998751/102467068-ce8ddc00-408a-11eb-91e8-3c68dd51bf74.png)

**Comment by shuoranliu** [comment]
fixed by #1098
