### ISSUE TITLE
10G dp always readonly

### ISSUE THREAD

**Issue by xrefft** [chubaofs/chubaofs#1094]
**Describe the bug**
We use a small-scale cluster to test CFS. In one test, we created a 10G dataPartition, which was allowed by the master. However, after creation, all dp are marked as read-only by the master, which triggers the `autoCreateDataPartitions()` of master. Finally, the dp of the entire cluster reached 3000+, resulting in node OOM.

**Environment**
3\*node (2C|8G|50GB docker container) ,  each node both have both master&meta&data.
 
**To Reproduce**
Just create volume that dpSize<=10(G).

**Comment by mervinkid** [comment]
This issue have been traced and will be fix in next release.

**Comment by xrefft** [comment]
> This issue have been traced and will be fix in next release.

Issue #1040 may raised by this bug. 

Maybe we should confirm if the `dpSize`<10GB when there are too much dp being created continuously.
