### ISSUE TITLE
cmd creates ump folder with wrong permissions

### ISSUE THREAD

**Issue by dbpaul** [chubaofs/chubaofs#111]
panic: init UMP Monitor failed open /cha/warn/ump_metanode_tp.log: permission denied [recovered]
	panic: init UMP Monitor failed open /cha/warn/ump_metanode_tp.log: permission denied

goroutine 1 [running]:
main.main.func1()
	/root/go/src/github.com/chubaofs/chubaofs/cmd/cmd.go:112 +0xc7
panic(0x9c49c0, 0xc0006e4a40)
	/usr/local/go/src/runtime/panic.go:522 +0x1b5
github.com/chubaofs/chubaofs/util/ump.InitUmp(0xc00053c060, 0x8, 0xc00053c0d0, 0xa)
	/root/go/src/github.com/chubaofs/chubaofs/util/ump/ump.go:62 +0xee
main.main()
	/root/go/src/github.com/chubaofs/chubaofs/cmd/cmd.go:139 +0x5ea

also :
```
panic: Failed to Open rocksDB! err:action[openRocksDB],err:IO error: No such file or directoryWhile mkdir if missing: /cha/Data/master/rocksdbstore: No such file or directory [recovered]
	panic: Failed to Open rocksDB! err:action[openRocksDB],err:IO error: No such file or directoryWhile mkdir if missing: /cha/Data/master/rocksdbstore: No such file or directory
```

the /cha/warn    /cha/log     /cha/Data directories do not exist when starting cmd.

ls -l 
drw-r--r--  2 owner owner    4096 Jun 20 11:57 warn/

some more friendly permissions
chmod a+x {warn,log}
mkdir -p /cha/Data/master
and 
./cmd -c master.json seems to work

I think the directory structure must be created before starting cmd or the directories must be checked and created correctly when starting cmd

master.json
```
{
  "role": "master",
  ...
"logDir": "/cha/log/master",
"warnLogDir":"/cha/warn/",
...
}
```

**Comment by awzhgw** [comment]
@dbpaul 
Our program must be started with the root account, because the datanode or metanode or master need to modify the maximum number of open file handles when starting. . .
