### ISSUE TITLE
使用docker方式安装集群失败

### ISSUE THREAD

**Issue by want-fly** [chubaofs/chubaofs#1113]
Checking datanode ... fail
[Data nodes]
ID        ADDRESS               WRITABLE    STATUS  
6         192.168.0.33:17310    No          Active  
7         192.168.0.31:17310    No          Active  
8         192.168.0.34:17310    No          Active  
9         192.168.0.32:17310    No          Active 

不知道怎么解决这个问题

**Comment by shuoranliu** [comment]
能否把运行的命令贴一下？以及机器配置？看是不是磁盘空间不够？

**Comment by want-fly** [comment]
> 能否把运行的命令贴一下？以及机器配置？看是不是磁盘空间不够？

启动命令为   docker/run_docker.sh -r -d /data/disk
应该是剩余磁盘空间不够 了 只剩 20g

**Comment by shuoranliu** [comment]
@want-fly I'm going to close this issue. Please feel free to re-open it if it does not work.
