### ISSUE TITLE
> Current platform FreeBSD not support

### ISSUE THREAD

**Issue by vermaden** [chubaofs/chubaofs#1114]
Please provide support for FreeBSD.

Minio works great on FreeBSD and it would also be great if your filesystem would.

Thanks.

**Comment by hooklee2000** [comment]
Pls specfic FreeBSD os 、gcc version and  cpu arch,. Would you like to make it then report the error info？

**Comment by vermaden** [comment]
I tried to build it on FreeBSD using your build instructions.

I needed to link **/bin/bash** to **/usr/local/bin/bash** as all your scripts hardcode to **#!/bin/bash** instead of something more corss platform like **#!/usr/bin/env bash** line.

As you require GNU make the GNU make is named **gmake** on FreeBSD.

```
% gmake
Current platform FreeBSD not support
build/build.sh: line 39: exit1: command not found
(scrtipt still running doing I do not know what)
```

So the script itself told me that it do not support FreeBSD and you have a typo in that section because instead of **exit 1** you have there **exit1** thus script did not ended after telling me that it does not support FreeBSD.

// GCC

I have two GCC versions installed:

```
% pkg info|grep gcc
gcc10-10.2.0                   GNU Compiler Collection 10
gcc48-4.8.5_13                 GNU Compiler Collection 4.8
```

// FreeBSD VERSION

```
% uname -prism
FreeBSD 13.0-BETA3 amd64 amd64 GENERIC
```

// ARCH
**amd64** - some call it **x86_64** or **x64**


Hope that helps.





> Current platform FreeBSD not support

**Comment by hooklee2000** [comment]
I found FreeBSD without

**Comment by vermaden** [comment]
Not sure.

**Comment by jadewang198510** [comment]
we recommend using chubaofs in Linux platform. FreeBSD is not support right now. @vermaden

**Comment by vermaden** [comment]
> we recommend using chubaofs in Linux platform. FreeBSD is not support right now. @vermaden

Thanks but as I prefer FreeBSD for server tasks I will just use GlusterFS along with Minio (for S3) instead of switching to Linux.

Thank you for reply tho.

Regards.
