### ISSUE TITLE
random write a bigger may cause creating a lot of datapartition

### ISSUE THREAD

**Issue by Victor1319** [chubaofs/chubaofs#1129]
**Describe the bug**
write model ```fio -directory=/home/service/chubaofs/wf/subvfmnt/ -ioengine=libaio -rw=randwrite -bs=64k -group_reporting=1 -fallocate=none -name=test_6 -numjobs=2 -nrfiles=1 -size=50G -direct=1 -runtime=30000```
I find there are a lot of extent's size is 64k in datapartitions, and dp's file count reach 20000 throld, so there will be a lot of dp created

**Comment by jadewang198510** [comment]
由于数据组织形态以及采用的覆盖写方式决定了会有这个问题，目前暂无修复方法。
