### ISSUE TITLE
Bug report 2.4 升级后metanode 内存占用过高

### ISSUE THREAD

**Issue by zcola** [chubaofs/chubaofs#1134]
/cfs/bin/cfs-server -v
ChubaoFS Server
Version : v2.4.0-rc.0
Branch  : master
Commit  : d80ff216deade0c86b38d557245f3dd8ded790a8
Build   : go1.15.6 linux amd64 2021-04-16 03:26

升级前（2.2 release）metanode内存占用 200G ，升级后 metanode  占用每天都在上升，第六天已经达到了 470G

**Comment by shuoranliu** [comment]
@zcola 感谢试用v2.4.0-rc.0，目前2.4.0还没有正式发布，还在测试中，这个还是rc版本。

不知道方便提供下go pprof heap吗？在metanode节点执行下面这个命令：

`wget http://<metanode ip地址>:<metanode prof端口号>/debug/pprof/heap`

**Comment by zcola** [comment]
原来是新开了一个端口但防火墙没打开导致删除meta 没成功
