### ISSUE TITLE
Build client Failed in v1.0.0

### ISSUE THREAD

**Issue by infavor** [chubaofs/chubaofs#1138]
- **Env:**

centos: 3.10.0-1160.el7.x86_64 x86_64
go: go1.16.4 linux/amd64

- **The steps to reproduce:**

git clone this project ; git checkout v1.0.0;
go mod init some_name
In Client directory, sh build.sh

- **What i got:**

 fuse.go:37:2: cannot find package "." in:
	/opt/chubaofs-1.0.0/chubaofs-1.0.0/vendor/github.com/chubaofs/cfs/client/fs
fuse.go:38:2: cannot find package "." in:
	/opt/chubaofs-1.0.0/chubaofs-1.0.0/vendor/github.com/chubaofs/cfs/util/config
fuse.go:39:2: cannot find package "." in:
	/opt/chubaofs-1.0.0/chubaofs-1.0.0/vendor/github.com/chubaofs/cfs/util/exporter
fuse.go:40:2: cannot find package "." in:
	/opt/chubaofs-1.0.0/chubaofs-1.0.0/vendor/github.com/chubaofs/cfs/util/log

- **What i tried:**

use cannot find package "." as keyword in google or stackoverflow, no solution found

**Comment by hooklee2000** [comment]
you can try the latest version v2.3.0，replace build.sh and build/build.sh with github main branch.
See #1125
