### ISSUE TITLE
install monitor failed

### ISSUE THREAD

**Issue by frankxieke** [chubaofs/chubaofs#1139]
**Describe the bug**
my os is red hat, i am using "bash install.sh -r monitor"
**Environment**

red hat 

**To Reproduce**
bash install.sh -r monitor

--2021-05-13 19:15:44--  http://storage.360buyimg.com/chubaofsrpm/latest/cfs-monitor-latest-el7.x86_64.rpm
正在解析主机 storage.360buyimg.com (storage.360buyimg.com)... 218.68.136.41, 2408:871a:5100:101::6548:c729
正在连接 storage.360buyimg.com (storage.360buyimg.com)|218.68.136.41|:80... 已连接。
已发出 HTTP 请求，正在等待回应... 200 OK
长度：10504 (10K) [application/octet-stream]
远程文件比本地文件 “cfs-monitor-latest-el7.x86_64.rpm” 更老 -- 不获取。

/cfs/install

PLAY [monitor] *********************************************************************************************************************************************************************************************

TASK [Gathering Facts] *************************************************************************************************************************************************************************************
ok: [10.178.6.27]

TASK [copy rpm package] ************************************************************************************************************************************************************************************
ok: [10.178.6.27]

TASK [install monitor rpm] *********************************************************************************************************************************************************************************
 [WARNING]: Consider using yum module rather than running yum

fatal: [10.178.6.27]: FAILED! => {"changed": true, "cmd": "yum install -y /opt/cfs/cfs-monitor-latest-el7.x86_64.rpm", "delta": "0:00:00.246362", "end": "2021-05-13 19:15:57.624226", "msg": "non-zero return code", "rc": 1, "start": "2021-05-13 19:15:57.377864", "stderr": "错误：无须任何处理", "stderr_lines": ["错误：无须任何处理"], "stdout": "已加载插件：fastestmirror, langpacks\n正在检查 /opt/cfs/cfs-monitor-latest-el7.x86_64.rpm: cfs-monitor-2.2.1-el7.x86_64\n/opt/cfs/cfs-monitor-latest-el7.x86_64.rpm：不更新已安装的软件包。", "stdout_lines": ["已加载插件：fastestmirror, langpacks", "正在检查 /opt/cfs/cfs-monitor-latest-el7.x86_64.rpm: cfs-monitor-2.2.1-el7.x86_64", "/opt/cfs/cfs-monitor-latest-el7.x86_64.rpm：不更新已安装的软件包。"]}
	to retry, use: --limit @/cfs/install/install_cfs.retry

PLAY RECAP *************************************************************************************************************************************************************************************************
10.178.6.27                : ok=2    changed=0    unreachable=0    failed=1

**Expected behavior**
install succeed

**Additional context**

**Comment by frankxieke** [comment]
looking forward to your relpy ,thanks

**Comment by frankxieke** [comment]
ping...

**Comment by hooklee2000** [comment]
Cfs monitor use prometheus and grafana. Maybe the verion of  prometheus or grafana  on your host is newer than the downloaded rpm. You can yum remove prometheus grafana then reinstall monitor. Or try to modify the ansible yaml file to ignore the rpm error.
