### ISSUE TITLE
meta node is unresponsive when no master available

### ISSUE THREAD

**Issue by dbpaul** [chubaofs/chubaofs#114]
./cmd -c meta.json

If no master in "masterAddrs" can be reached, cmd becomes unreponsive (no ctrl-c) and can only be killed with kill -9

In addition metaNode_error.log and metaNode_debug.log rapidly fill up until no more disk space is left. 

maybe cmd can just quit if no master is available or try to reach a master for a certain time before it quits

**Comment by dbpaul** [comment]
started as a datanode, has the same problem.

**Comment by awzhgw** [comment]
it is a good idea.   We will change in the next version.

**Comment by dbpaul** [comment]
It is ok that the master has to start first.
I the design is that the master needs to start first, then the metanode should not start when the master is not started.
