### ISSUE TITLE
dataserver fail to start when one mount point does not exist - no message in error log

### ISSUE THREAD

**Issue by dbpaul** [chubaofs/chubaofs#115]
datanode.json
```
"disks": [
        "/mnt/btrfs/cha1:2474836480",
        "/doesnotexist:21474836480"
    ]
```
{1024 1048576}
Rlimit Final {1024000 1024000}
Fatal: failed to start the baud storage daemon -  bad config file

1) the error message could actually say what the problem is
2) there is no error message in the dataNode_error.log

**Comment by awzhgw** [comment]
#121 fixed
