### ISSUE TITLE
what is datanode REST_SIZE?

### ISSUE THREAD

**Issue by dbpaul** [chubaofs/chubaofs#116]
There is no description of REST_SIZE in the datanode config json file.
Is this the maximum usable filesystem size for chubaofs? Measured in bytes?

**Comment by awzhgw** [comment]
@dbpaul  it is the disk Reserved size.  when disk used size has exceed (total-rest_size),then the disk Marked as full

**Comment by awzhgw** [comment]
#118  it will be fixed
