### ISSUE TITLE
Memory anonpage increases periodically

### ISSUE THREAD

**Issue by leonrayang** [chubaofs/chubaofs#1168]
The online follow-up of the memory exception problem of cluster datanode and metanode shows that the memory anonpage is high, which causes the release of GC and cache. Pprof shows that the raft receive buffer is full

**Comment by leonrayang** [comment]
![image](https://user-images.githubusercontent.com/12113219/122852413-26134a00-d343-11eb-82e9-47827ddc0549.png)
![image](https://user-images.githubusercontent.com/12113219/122852439-30cddf00-d343-11eb-9226-6bd17dd8023d.png)

**Comment by leonrayang** [comment]
![image](https://user-images.githubusercontent.com/12113219/122852516-522ecb00-d343-11eb-9af1-861ccb6a3b36.png)

**Comment by zcola** [comment]
是不是开了 THP 内存透明大页

**Comment by leonrayang** [comment]
没开大页，另外我看大页的问题是性能问题，https://cloud.tencent.com/developer/article/1721462
这里有个待验证的地方，协议的header的解包没有校验的，如果是错误的包，body长度过长，会申请大buffer

**Comment by leonrayang** [comment]
直接原因是端口扫描导致，raft server的端口没有check协议的正确性
优化项目
1）后续需要增加crc以校验raft server的收包
2）另外，也发现了，包括client端到服务端的协议解包部分，例如datanode协议部分的check是针对body，且是在prepare之后，这个时候内存都已经allocate完毕，影响已经形成，需要header部分也要增加crc校验

`raft_warn.log.202107180004:2021-07-18 12:43:19,129 codec.go:234: [WARN.] action[Message.Decode] buffer exceed! data len [1195986768],addr [10.177.148.234:36112]
raft_warn.log.202107180004:2021-07-18 12:43:19,129 codec.go:234: [WARN.] action[Message.Decode] buffer exceed! data len [1195986768],addr [10.177.148.234:41592]
raft_warn.log.202107180004:2021-07-18 12:43:24,621 codec.go:234: [WARN.] action[Message.Decode] buffer exceed! data len [1195725856],addr [10.177.148.234:49160]
raft_warn.log.202107180004:2021-07-18 12:43:24,621 codec.go:234: [WARN.] action[Message.Decode] buffer exceed! data len [1195725856],addr [10.177.148.234:43724]
raft_warn.log.202107180004:2021-07-18 12:43:31,892 codec.go:234: [WARN.] action[Message.Decode] buffer exceed! data len [2147483688],addr [10.177.148.234:56770]
raft_warn.log.202107180004:2021-07-18 12:43:31,892 codec.go:234: [WARN.] action[Message.Decode] buffer exceed! data len [2147483688],addr [10.177.148.234:34032]`
