### ISSUE TITLE
master supports deleting miss copies

### ISSUE THREAD

**Issue by jadewang198510** [chubaofs/chubaofs#1272]
**Is your feature request related to a problem? Please describe.**
1. Due to the non-atomic nature of offline operations, there will be a scenario where three hosts and two replicas are recorded on the master. This need will be able to offline an abnormal copy.
2. If there are 3 copies of a partition, and the node to which a copy belongs is stopped for more than one minute (downtime), the partition on this abnormal node cannot be migrated and needs to be repaired

**Describe the solution you'd like**

The number of copies is N.
To
1. Under the premise that the number of available copies is greater than >= N/2 +1, it is supported to delete missed copies.
2. When adding copies, the total number of copies (including those that have been missed) cannot exceed N.
3. Support meta and data.

**Comment by Victor1319** [comment]
fixed by #1285
