### ISSUE TITLE
create data partition fails when only one datanode available run_test.sh does not catch the error

### ISSUE THREAD

**Issue by dbpaul** [chubaofs/chubaofs#128]
- I could not find any documentation on how many datanodes(or disks?) need to be available.
- using the configuration files from chubaofs/docker/conf/ with different ips
- creating 2 masters, 3 metaservers, one datanode
- then running run_test.sh
- it shows create datapartition ok, but the partition is not created.

curl -v "http://192.168.0.131:17010/dataPartition/create?count=400&name=ltptest"

{"code":0,"msg":"success","data":" createDataPartition succeeeds. clusterLastTotalDataPartitions[0],vol[ltptest] has 0 data partitions previously and 0 data partitions now \n err[action[createDataPartition],clusterID[ltptest] vol[ltptest] Err:[cluster.go 550] no node set available for creating a data partition ]"}

log:
`[ERROR] cluster.go:495: action[createDataPartition],clusterID[ltptest] vol[ltptest] Err:[cluster.go 550] no node set available for creating a data partition
`

curl -v "http://192.168.0.131:17010/admin/getCluster" | python -m json.tool

```
{
    "code": 0,
    "data": {
        "Applied": 23,
        "BadPartitionIDs": [],
        "DataNodeStatInfo": {
            "IncreasedGB": 0,
            "TotalGB": 7373,
            "UsedGB": 1949,
            "UsedRatio": "0.264"
        },
        "DataNodes": [
            {
                "Addr": "192.168.0.102:17310",
                "ID": 3,
                "IsWritable": true,
                "Status": true
            }
        ],
        "DisableAutoAlloc": false,
        "LeaderAddr": "192.168.0.131:17010",
        "MaxDataPartitionID": 0,
        "MaxMetaNodeID": 6,
        "MaxMetaPartitionID": 3,
        "MetaNodeStatInfo": {
            "IncreasedGB": 0,
            "TotalGB": 23,
            "UsedGB": 0,
            "UsedRatio": "0.004"
        },
        "MetaNodeThreshold": 0.75,
        "MetaNodes": [
            {
                "Addr": "192.168.0.119:17210",
                "ID": 4,
                "IsWritable": true,
                "Status": true
            },
            {
                "Addr": "192.168.0.127:17210",
                "ID": 2,
                "IsWritable": true,
                "Status": true
            },
            {
                "Addr": "192.168.0.137:17210",
                "ID": 5,
                "IsWritable": true,
                "Status": true
            }
        ],
        "Name": "ltptest",
        "VolStatInfo": [
            {
                "Name": "ltptest",
                "TotalGB": 30,
                "UsedGB": 0,
                "UsedRatio": "0.000"
            }
        ]
    },
    "msg": "success"
}
```

**Comment by awzhgw** [comment]
Minimum 4 datanodes required
We have updated in the documentation

**Comment by dbpaul** [comment]
How many metanodes are required? The same error is there when there is only one metanode and you try to create a volume.

**Comment by dbpaul** [comment]
In the documentation it says "At least 4 data nodes are required in respect to high availability." Does this mean 4 datanodes are the minimum amount?

**Comment by awzhgw** [comment]
@dbpaul  yes.
