### ISSUE TITLE
build CFS error: cannot find -lbz2 cannot find -lsnappy

### ISSUE THREAD

**Issue by heidawei** [chubaofs/chubaofs#137]
sh build.sh 
# github.com/chubaofs/chubaofs/vendor/github.com/tecbot/gorocksdb
/usr/bin/ld: cannot find -lbz2
/usr/bin/ld: cannot find -lsnappy
collect2: 错误：ld 返回 1

**Comment by awzhgw** [comment]
#140 will fixed
