### ISSUE TITLE
cd cmd;sh build.sh --- go:error loading module requirements

### ISSUE THREAD

**Issue by halleyshx** [chubaofs/chubaofs#142]
[ root@A01-R02-I182-64-CX5PD92 cmd]# sh build. shgo: finding github. com/kylelemons/godebug v1.1.0
go: finding github. com/facebookgo/stack v0.0.0-20160209184415-751773369052
go: finding github. com/smartystreets/goconvey v0.0.0-20190330032615-68dc04aab96a go: finding github. com/parnurzeal/gorequest vo.2.15
go: finding github. com/google/btree v1.0.0
go: finding github. com/jacobsa/fuse v0.0.0-20180417054321-cd3959611bcb go: finding github. com/elazarl/goproxy/ext v0.0.0-20190421051319-9d40249d3c2f go: finding github. com/tecbot/gorocksdb v0.0.0-20190519120508-025c3cf4ffb4
go: finding bazil. org/fuse v0.0.0-20180421153158-65cc252bf669
go: golang. org/x/net@v0.0.0-20190619014844-b5b0513f8c1b: unrecognized import path "golang. org/x/net"(https fetch: Get https://golang. org/x/net? go-get=1: dial tcp 216.239.37.1:443: connect: connection timed out)
go: finding github. com/tiglabs/raft v0.0.0-20190131082128-45667fcdb8b8
go: finding github. com/elazarl/goproxy v0.0.0-20190421051319-9d40249d3c2f go: finding github. com/prometheus/client_golang v1.0.0
go: finding github. com/facebookgo/subset v0.0.0-20150612182917-8dac2c3c4870
go: finding github. com/moul/http2curl v1.0.0
go: finding github. com/facebookgo/ensure v0.0.0-20160127193407-b4ab57deab51
go: error loading module requirements

**Comment by awzhgw** [comment]
set GOPATH  can fix it
