### ISSUE TITLE
build.sh in cmd must change

### ISSUE THREAD

**Issue by halleyshx** [chubaofs/chubaofs#143]
[root@A01-R02-I182-64-CX5PD92 cmd]# sh build.sh
# github.com/chubaofs/chubaofs/vendor/github.com/tecbot/gorocksdb
/usr/local/lib/librocksdb.a(db_impl.o): In function `ZSTD_Supported':
/export/servers/temp/rocksdb/./util/compression.h:88: undefined reference to `ZSTD_versionNumber'
/usr/local/lib/librocksdb.a(options_helper.o): In function `ZSTD_Supported':
/export/servers/temp/rocksdb/./util/compression.h:88: undefined reference to `ZSTD_versionNumber'
/usr/local/lib/librocksdb.a(format.o): In function `ZSTD_Uncompress':
/export/servers/temp/rocksdb/./util/compression.h:783: undefined reference to `ZSTD_createDCtx'
/export/servers/temp/rocksdb/./util/compression.h:786: undefined reference to `ZSTD_decompress_usingDict'
/export/servers/temp/rocksdb/./util/compression.h:787: undefined reference to `ZSTD_freeDCtx'
/usr/local/lib/librocksdb.a(format.o): In function `LZ4_Uncompress':
/export/servers/temp/rocksdb/./util/compression.h:617: undefined reference to `LZ4_createStreamDecode'
/export/servers/temp/rocksdb/./util/compression.h:624: undefined reference to `LZ4_decompress_safe_continue'
/export/servers/temp/rocksdb/./util/compression.h:625: undefined reference to `LZ4_freeStreamDecode'
/export/servers/temp/rocksdb/./util/compression.h:617: undefined reference to `LZ4_createStreamDecode'
/export/servers/temp/rocksdb/./util/compression.h:624: undefined reference to `LZ4_decompress_safe_continue'
/export/servers/temp/rocksdb/./util/compression.h:625: undefined reference to `LZ4_freeStreamDecode'
/export/servers/temp/rocksdb/./util/compression.h:620: undefined reference to `LZ4_setStreamDecode'
/export/servers/temp/rocksdb/./util/compression.h:620: undefined reference to `LZ4_setStreamDecode'
/usr/local/lib/librocksdb.a(column_family.o): In function `ZSTD_Supported':
/export/servers/temp/rocksdb/./util/compression.h:88: undefined reference to `ZSTD_versionNumber'
/export/servers/temp/rocksdb/./util/compression.h:88: undefined reference to `ZSTD_versionNumber'
/usr/local/lib/librocksdb.a(block_based_table_builder.o): In function `ZSTD_Compress':
/export/servers/temp/rocksdb/./util/compression.h:746: undefined reference to `ZSTD_compressBound'
/export/servers/temp/rocksdb/./util/compression.h:750: undefined reference to `ZSTD_createCCtx'
/export/servers/temp/rocksdb/./util/compression.h:753: undefined reference to `ZSTD_compress_usingDict'
/export/servers/temp/rocksdb/./util/compression.h:754: undefined reference to `ZSTD_freeCCtx'
/usr/local/lib/librocksdb.a(block_based_table_builder.o): In function `LZ4_Compress':
/export/servers/temp/rocksdb/./util/compression.h:552: undefined reference to `LZ4_compressBound'
/export/servers/temp/rocksdb/./util/compression.h:557: undefined reference to `LZ4_createStream'
/export/servers/temp/rocksdb/./util/compression.h:565: undefined reference to `LZ4_compress_fast_continue'
/export/servers/temp/rocksdb/./util/compression.h:571: undefined reference to `LZ4_freeStream'
/usr/local/lib/librocksdb.a(block_based_table_builder.o): In function `LZ4HC_Compress':
/export/servers/temp/rocksdb/./util/compression.h:671: undefined reference to `LZ4_compressBound'
/export/servers/temp/rocksdb/./util/compression.h:676: undefined reference to `LZ4_createStreamHC'
/export/servers/temp/rocksdb/./util/compression.h:677: undefined reference to `LZ4_resetStreamHC'
/export/servers/temp/rocksdb/./util/compression.h:682: undefined reference to `LZ4_loadDictHC'
/export/servers/temp/rocksdb/./util/compression.h:687: undefined reference to `LZ4_compress_HC_continue'
/export/servers/temp/rocksdb/./util/compression.h:693: undefined reference to `LZ4_freeStreamHC'
/usr/local/lib/librocksdb.a(block_based_table_builder.o): In function `LZ4_Compress':
/export/servers/temp/rocksdb/./util/compression.h:560: undefined reference to `LZ4_loadDict'
collect2: error: ld returned 1 exit status

-----
change build.sh
`CGO_CFLAGS="-I/usr/local/include" CGO_LDFLAGS="-L/usr/local/lib -lrocksdb -lstdc++ -lm -lz -lbz2 -lzstd -llz4" go build -ldflags "-X main.CommitID=${CommitID} -X main.BranchName=${BranchName} -X 'main.BuildTime=${BuildTime}'" -o cfs-server`
it can work

**Comment by awzhgw** [comment]
#171  will fixed
