### ISSUE TITLE
CFS not support windows and mac os

### ISSUE THREAD

**Issue by heidawei** [chubaofs/chubaofs#144]
CFS will use Hole Punching for delete small file, but the macos do not support this API in systemcall

**Comment by awzhgw** [comment]
yes, it can only support centos

**Comment by sjqzhang** [comment]
可以用用go-fastdfs试试

**Comment by mervinkid** [comment]
> CFS will use Hole Punching for delete small file, but the macos do not support this API in systemcall

Thanks for your feedback.

Yes indeed, the **Linux** kernel based operating system is required currently.

We propose to use our docker tool script `run_docker.sh` under the `docker` folder. It makes ability to build **ChubaoFS** or run a minimal cluster with full components on your local docker environment by single command.
