### ISSUE TITLE
build fails

### ISSUE THREAD

**Issue by dbpaul** [chubaofs/chubaofs#182]
git clone http://github.com/chubaofs/chubaofs.git
cd chubaofs/
make

build snappy...
build/build.sh: line 19: cmake: command not found
build snappy failed
Makefile:9: recipe for target 'build' failed
make: *** [build] Error 1

**Comment by awzhgw** [comment]
please install snappy

**Comment by mervinkid** [comment]
> git clone [http://github.com/chubaofs/chubaofs.git](https://github.com/chubaofs/chubaofs.git)
> cd chubaofs/
> make
> 
> build snappy...
> build/build.sh: line 19: cmake: command not found
> build snappy failed
> Makefile:9: recipe for target 'build' failed
> make: *** [build] Error 1

Thanks for feedback.

Cmake is required in building `rocksdb` and it's dependencies. 
We use rocksdb to store cluster topology information at the **Resource Manager**(Master).
