### ISSUE TITLE
Requries authentication mechanism in a safe network environment

### ISSUE THREAD

**Issue by shuoranliu** [chubaofs/chubaofs#253]
We need an authentication mechanism to address the following issues:

- Sometimes there are tens of thousands of clients accessing the same volume, and some **STALE** mounted clients are a potential threat to data safety.
- Some admin requests to master nodes are dangerous which requires authentication.

Therefore, we would like to introduce a new role called *authnode* to provide authentication capability. 

It is important to clearify that assume we are in a safe network environment. So issues from an unsafe network environment such as hacking are out of the scope of this issue, and might be tracked by a new issue if needed.

**Comment by jadewang198510** [comment]
already support use ak&sk for authentication
