### ISSUE TITLE
Feature request: object storage interface

### ISSUE THREAD

**Issue by bladehliu** [chubaofs/chubaofs#263]
S3-like object storage interface to ChubaoFS

**Comment by bladehliu** [comment]
moreover, to support billions of buckets, the metadata subsystem architecture needs to be refactored -  partition:namespace from 1:1 to 1:n.

**Comment by mervinkid** [comment]
> S3-like object storage interface to ChubaoFS

The development of S3-compatible is in progress, which makes ChubaoFS provides high-level API based on http protocol. 

It is designed to be compatible with native Amazon S3 interfaces, so that user can use the Amazon S3 protocol and POSIX protocol to operate ChubaoFS at the same time.

This feature will be released at late of 2019.

**Comment by wding109** [comment]
We need to put the design doc into the repo.

**Comment by mervinkid** [comment]
> We need to put the design doc into the repo.

The design document and code of this feature have been pushed into [`s3` branch](https://github.com/chubaofs/chubaofs/tree/s3).

**Comment by mervinkid** [comment]
The interfaces for file data operations has been completed and merge to `master` branch by pull request #320 .

Following interface haven been supported:

- HeadBucket
- GetBucketLocation
- HeadObject
- PutObject
- GetObject
- ListObjects
- ListObjectsV2
- DeleteObject
- DeleteObjects
- CopyObject
- CreateMultipartUpload
- ListMultipartUploads
- AbortMultipartUpload
- CompleteMultipartUpload
- ListParts
- UploadPart
- UploadPartCopy

We are working on **Policy**&**ACL** related functions and it will be done soon.

**Comment by mervinkid** [comment]
> > We need to put the design doc into the repo.
> 
> The design document and code of this feature have been pushed into [`s3` branch](https://github.com/chubaofs/chubaofs/tree/s3).

Notes:
The document about design and user guide of object subsystem which provides s3-compatible object storage interface have been merged to **master** branch.
