### ISSUE TITLE
Feature request: web console for operations

### ISSUE THREAD

**Issue by Vivian7755** [chubaofs/chubaofs#267]

**Comment by mervinkid** [comment]
Development of web based console and command line interface is in progress.

**Comment by mervinkid** [comment]
Rename this issue to "feature request: console for operations".

**Comment by mervinkid** [comment]
This feature request related with issue #269 .
A dashboard will be included in web console component.

**Comment by mervinkid** [comment]
The prototype of the console component has been designed by @Vivian7755  and finalized by all the maintainers.
Front-end development work is assigned to the front-end team for scheduling.
The server development work is assigned to @ansjsun and @wenjia322 .
