### ISSUE TITLE
Provide dashboard

### ISSUE THREAD

**Issue by Vivian7755** [chubaofs/chubaofs#269]

**Comment by paulocoghi** [comment]
I can contribute with the dashboard development. I would like an opinion from the main developers to know if they are interested.

**Comment by Vivian7755** [comment]
@paulocoghi Welcome, Could you join Chubaofs.slack .com, then we can have more discussion

**Comment by mervinkid** [comment]
> I can contribute with the dashboard development. I would like an opinion from the main developers to know if they are interested.
> 
> Ping @mervinkid

Hi, I sent an invitation of **chubaofs.slack.com** to your email.

**Comment by mervinkid** [comment]
Dashboard will be provided by console component.
This issue related with issue(#267).
