### ISSUE TITLE
Enable DCO checks on repo

### ISSUE THREAD

**Issue by caniszczyk** [chubaofs/chubaofs#313]
It is a requirement for CNCF to have the project enforce DCO.

https://developercertificate.org/

**Comment by wding109** [comment]
We already enabled DCO, any commit needs a `Signed-off-by` at this point.  But for some reason DCO is not shown as `enabled` in our repo. Let's just redo it - add DCO (https://probot.github.io/apps/dco/) to our github repo.  @awzhgw  this requires admin permission

**Comment by awzhgw** [comment]
@caniszczyk  @wding109  it has enabled

**Comment by mervinkid** [comment]
> It is a requirement for CNCF to have the project enforce DCO.
> 
> https://developercertificate.org/

The DCO check is already enabled.
