### ISSUE TITLE
is there any prebuild binaries to download ?

### ISSUE THREAD

**Issue by carr123** [chubaofs/chubaofs#321]
I don't want to build from souce. just for convinence.

**Comment by mervinkid** [comment]
> I don't want to build from souce. just for convinence.

Hi, @carr123 

Thanks for your feedback.

We have provided faster and more convenient solutions based on [docker](https://www.docker.com) and [kubernetes](https://kubernetes.io) to avoid users from building projects themselves.

You can quickly start a full component included and configured ChubaoFS cluster on your local **docker** environment with just one command by using our docker script `run_docker.sh` under the docker folder. Detail about using out docker tool script see [ChubaoFS Document - User Guide - Docker](https://chubaofs.readthedocs.io/en/latest/user-guide/docker.html).

**Example**
Start a minimal ChubaoFS cluster from scratch.
```bash
 $ docker/run_docker.sh -r -d /data/disk
```
>Note that /data/disk is arbitrary, and make sure there are at least 30G available space.

**Comment by carr123** [comment]
good job
