### ISSUE TITLE
User Guide is not up-to-date about the configuration of DataNode, MetaNode and Client

### ISSUE THREAD

**Issue by chengyu-l** [chubaofs/chubaofs#346]
**Is your feature request related to a problem? Please describe.**
NA

**Describe the solution you'd like**
Add the introduction of new parameters of DataNode, MetaNode and Client, in release 1.5.0

**Describe alternatives you've considered**
NA

**Additional context**
NA

**Comment by awzhgw** [comment]
@chengyu-l  the authorNode current not Enable,so ,the configFile use old configure
