### ISSUE TITLE
Create basic website for CFS

### ISSUE THREAD

**Issue by caniszczyk** [chubaofs/chubaofs#35]
It would be great to have a simple hugo website for CFS

I can have @lucperkins spin something up for the project

**Comment by Vivian7755** [comment]
Hi Luc Perkins, if you need more detail materials for the websie for CFS, please just let me know, thanks  :)

**Comment by lucperkins** [comment]
@Vivian7755 Please provide any details you have handy. Are you looking for just a landing page or something more? Do you have any visual materials like logos, color schemes, etc.?

**Comment by Vivian7755** [comment]
@lucperkins  https://cfs.readthedocs.io/en/latest/  Here is the docs, and logo is on designing. When we finish the logo design, I will send you at first time and then you can refer to that color schemes.

**Comment by lucperkins** [comment]
@Vivian7755 So are you just looking for a home page that links to those docs?

**Comment by wding109** [comment]
@lucperkins We want to have an entirely new design of our website, and the theme on the home page should be consistent with the ones on the rest pages such as documentation, FAQs, etc. We are currently using the default theme in readthedocs for documentation, but we want to replace it.

**Comment by lucperkins** [comment]
@wding109 I can provide a home page but I unfortunately won't be able to provide themed documentation at this time.

**Comment by wding109** [comment]
@lucperkins That's a great help already! Thanks a lot!

**Comment by lucperkins** [comment]
@wding109 No problem! I'm very happy to help with this very interesting. I may be able to do more on the docs side at some point!

**Comment by Vivian7755** [comment]
@lucperkins  I have sent the logo design files to your email (lucperkins@gmail.com), please help to double check , thanks  :)

**Comment by bladehliu** [comment]
http://chubao.io/
