### ISSUE TITLE
Feature request - support volumes of different replica degrees

### ISSUE THREAD

**Issue by bladehliu** [chubaofs/chubaofs#376]
**Is your feature request related to a problem? Please describe.**
Some applications may prefer volumes of 2 data replicas rather than 3

**Describe the solution you'd like**
specify the replication degree (2 or 3) as well as the write mode (sequential or random) when creating a volume. 

so the cluster master needs to support volumes of different types

**Comment by awzhgw** [comment]
it has merged..so i will close this issue. @bladehliu
