### ISSUE TITLE
Feature request: ARM and ARM64 architecture support

### ISSUE THREAD

**Issue by dereulenspiegel** [chubaofs/chubaofs#393]
I had a quick look at this project and I like it. However I saw only x86_64 images on docker hub. Wouldn't it be easily possible to build this project for ARM/ARM64 and provide multi arch images?
This would probably be awesome for everyone who tries to run cluster with k3s and similar offerings on ARM clusters.

**Comment by awzhgw** [comment]
@dereulenspiegel  Thank you for your suggestion
We Will try to do this thins.

**Comment by mervinkid** [comment]
Hi @dereulenspiegel ,

Thanks for your feedback.

Unfortunately, we have not adapted ChubaoFS to the ARM and ARM64 platform yet.

We hope that ChubaoFS can help users in more scenarios. But we are not very familiar with the scenarios of these platforms you mentioned. 

Can you elaborate on the dozens of user scenarios and requirements of these platforms you mentioned.

**Comment by dereulenspiegel** [comment]
Hi @mervinkid 

thank you for your quick response. There are multiple scenarios where a distributed storage system on ARM(64) would be valuable.
First there are more and more cloud provider offering ARM based servers (Amazon, Scaleway, probably a few others). Making ChubaoFS available for ARM based platforms would make it the prime choice for running distributed storage on pure ARM or even mixed ARM/x86 clusters.
Also the need for edge computing is pushing for more and more infrastructure on the like. In these scenarios x86 is not always the best choice. Bringing K8s/k3s with reliable distributed storage would very likely benefit many scenarios on the infrastructure edge.
Lastly a small ARM based k8s cluster is great development environment. Unfortunately we are lacking reliable distributed storage here.

I hope that this helps assessing if a port to ARM based platforms would be worth it for you. I surely hope so.

**Comment by mervinkid** [comment]
Hi @dereulenspiegel 
Thank you for your explanation, I understand and think this is interesting.
Do you have any experience in adapting the Go language project to ARM and ARM64 platforms?
We would love to have a deeper discussion with you.
If you like, we also hope you can join and complete this adaptation.

**Comment by dereulenspiegel** [comment]
If ChubaoFS only has Go based dependencies, then porting to ARM/ARM64 should be quite easy. Go itself has cross compiling capabilities, simply by setting the environment variable `GOARCH` to `arm` or  `arm64` should be sufficient to tell the compiler to produce ARM-compatible binaries. Only if cgo is involved, things get more complicated.
Otherwise running the build on an ARM-Server should produce ARM-Binaries. I am absolutely willing to test this and provide feedback, once a first build is available.

**Comment by mervinkid** [comment]
It seems things get more complicated cause cgo is involved in ChubaoFS.
In the ChubaoFS project, we use **rocksdb** as the storage engine for the resource manager (Master), and our mountable client depends on **libfuse**.
Much work remains to be done in adaption.
We will discuss further work on adaptation.

**Comment by dereulenspiegel** [comment]
I had a quick look if I can build ChubaoFS in an ARM64 environment. So I spun up a container with `docker run -ti golang:1.14.0-stretch@sha256:05021034c1bdf9d08de5971b297d6167ee0f50042cb4b21f804f171fcc31d9a1 /bin/bash` which gives me an ARM64 environment.
After `apt-get update && apt-get upgrade && apt-get install cmake libz-dev libbz2-dev` Building the sub project snappy and rocksdb works well. Unfortunately the `syscall` in Go seems to be quite platform specific.
The `dup2` syscall doesn't seem to exist when running in an ARM64 environment, causing the build to fail.
Unfortunately right now I don't feel competent within this project to know how to replace the `dup2` with something more platform agnostic, probably we can try replacing it with dup3 if such low level operations are really necessary.
But so far it probably isn't too complicated, if the dup2 syscall is replaced.

**Comment by mervinkid** [comment]
> I had a quick look if I can build ChubaoFS in an ARM64 environment. So I spun up a container with `docker run -ti golang:1.14.0-stretch@sha256:05021034c1bdf9d08de5971b297d6167ee0f50042cb4b21f804f171fcc31d9a1 /bin/bash` which gives me an ARM64 environment.
> After `apt-get update && apt-get upgrade && apt-get install cmake libz-dev libbz2-dev` Building the sub project snappy and rocksdb works well. Unfortunately the `syscall` in Go seems to be quite platform specific.
> The `dup2` syscall doesn't seem to exist when running in an ARM64 environment, causing the build to fail.
> Unfortunately right now I don't feel competent within this project to know how to replace the `dup2` with something more platform agnostic, probably we can try replacing it with dup3 if such low level operations are really necessary.
> But so far it probably isn't too complicated, if the dup2 syscall is replaced.

Thanks for your contribution to ChubaoFS.

**Comment by mervinkid** [comment]
@dereulenspiegel 

The file `vendor/github.com/tiglabs/raft/util/log/log_crash_unix.go` you mentioned is PR #398 is part of the raft library which also maintained by us.
We are going to fix the code to under this library according to your suggestions.

**Comment by mervinkid** [comment]
@dereulenspiegel 

We have replaced `syscall.Dup2` with `syscall.Dup3` from file `vendor/github.com/tiglabs/raft/util/log/log_crash_unix.go` by PR(#401) and already merged to `master` branch.

**Comment by mervinkid** [comment]
Rename this issue to "**feature request: ARM and ARM64 architecture support**".

**Comment by mervinkid** [comment]
PR #779 tries to achieve compatibility with the ARM platform, and this PR is being reviewed.

**Comment by mervinkid** [comment]
The pull request #779 haven been applied and merged into `master` branch.
