### ISSUE TITLE
Feature request: support extend attribute (xattr)

### ISSUE THREAD

**Issue by mervinkid** [chubaofs/chubaofs#425]
**Is your feature request related to a problem? Please describe.**:

Some system software uses extended attributes (**xattr**) to implement some advanced features.

Reference:
[Extended file attributes - Wikipedia](https://en.wikipedia.org/wiki/Extended_file_attributes)
[xattr(7) - Linux manual page](http://man7.org/linux/man-pages/man7/xattr.7.html)

**Describe the solution you'd like**

Implement extend attributes (**xattr**) support to metadata and posix-compatible file system interface (mountable client).

**Describe alternatives you've considered**

NONE.

**Additional context**

NONE.

**Comment by bladehliu** [comment]
yes we need this feature, thank you.

**Comment by mervinkid** [comment]
@bladehliu 

This feature have been developed and included in `object-store` branch. 
It will be merged into master branch soon by PR #420 .
