### ISSUE TITLE
提供一个详细点的说明文档

### ISSUE THREAD

**Issue by sxb12345** [chubaofs/chubaofs#486]
提供一个详细点的说明文档
1、例如像yum安装就一句话，后面怎么调用，没说了
2、列几个使用场景，一步一步，如何调用，例如从第一步开始到结束
使用场景，比如网站或应用程序（例如知识库），长传文件到这个分布式存储上，有一台坏了，不丢失，还能读写

**Comment by mervinkid** [comment]
@sxb12345 

Thanks for your feedback.
Your suggestion is very important to us.
There are a lot of incomplete contents in the current project's documentation, and the content you mentioned will be added in the documentation.
We are going to reorganize the document structure to make the document readability and content context better.

**Comment by sxb12345** [comment]
datanode can't start 
2020/04/17 19:01:32.270126 [ERROR] cluster.go:562: action[createDataPartition],clusterID[chubaofsxb01] vol[ltptest] Err:[cluster.go 597] no node set available for creating a data partition 
2020/04/17 19:01:32.270147 [ERROR] topology.go:239: action[allocNodeSetForDataNode],err:no node set available for creating a data partition
2020/04/17 19:01:32.270154 [ERROR] cluster.go:562: action[createDataPartition],clusterID[chubaofsxb01] vol[ltptest] Err:[cluster.go 597] no node set available for creating a data partition 
2020/04/17 19:01:32.270171 [ERROR] topology.go:239: action[allocNodeSetForDataNode],err:no node set available for creating a data partition
2020/04/17 19:01:32.270177 [ERROR] cluster.go:562: action[createDataPartition],clusterID[chubaofsxb01] vol[ltptest] Err:[cluster.go 597] no node set available for creating a data partition 
2020/04/17 19:01:32.270193 [ERROR] topology.go:239: action[allocNodeSetForDataNode],err:no node set available for creating a data partition
2020/04/17 19:01:32.270199 [ERROR] cluster.go:562: action[createDataPartition],clusterID[chubaofsxb01] vol[ltptest] Err:[cluster.go 597] no node set available for creating a data partition 
2020/04/17 19:01:32.270214 [ERROR] topology.go:239: action[allocNodeSetForDataNode],err:no node set available for creating a data partition
2020/04/17 19:01:32.270220 [ERROR] cluster.go:562: action[createDataPartition],clusterID[chubaofsxb01] vol[ltptest] Err:[cluster.go 597] no node set available for creating a data partition 
2020/04/17 19:01:32.270237 [ERROR] topology.go:239: action[allocNodeSetForDataNode],err:no node set available for creating a data partition
2020/04/17 19:01:32.270250 [ERROR] cluster.go:562: action[createDataPartition],clusterID[chubaofsxb01] vol[ltptest] Err:[cluster.go 597] no node set available for creating a data partition 
2020/04/17 19:01:32.270266 [ERROR] topology.go:239: action[allocNodeSetForDataNode],err:no node set available for creating a data partition
2020/04/17 19:01:32.270272 [ERROR] cluster.go:562: action[createDataPartition],clusterID[chubaofsxb01] vol[ltptest] Err:[cluster.go 597] no node set available for creating a data partition 
2020/04/17 19:01:32.270288 [ERROR] topology.go:239: action[allocNodeSetForDataNode],err:no node set available for creating a data partition
2020/04/17 19:01:32.270294 [ERROR] cluster.go:562: action[createDataPartition],clusterID[chubaofsxb01] vol[ltptest] Err:[cluster.go 597] no node set available for creating a data partition 
2020/04/17 19:01:32.270308 [ERROR] topology.go:239: action[allocNodeSetForDataNode],err:no node set available for creating a data partition
2020/04/17 19:01:32.270314 [ERROR] cluster.go:562: action[createDataPartition],clusterID[chubaofsxb01] vol[ltptest] Err:[cluster.go 597] no node set available for creating a data partition 
2020/04/17 19:01:32.270328 [ERROR] topology.go:239: action[allocNodeSetForDataNode],err:no node set available for creating a data partition
2020/04/17 19:01:32.270334 [ERROR] cluster.go:562: action[createDataPartition],clusterID[chubaofsxb01] vol[ltptest] Err:[cluster.go 597] no node set available for creating a data partition 
2020/04/17 19:02:32.247362 [ERROR] consul_register.go:125: Error on register consul resp: Put http://172.28.168.152:8500/v1/agent/service/register: dial tcp 172.28.168.152:8500: connect: connection refused,
