### ISSUE TITLE
[已弃坑]希望客户端能提供IO性能监控

### ISSUE THREAD

**Issue by zcola** [chubaofs/chubaofs#495]
在本地磁盘中，我们可以很轻松获取到读写 IOPS 和IO 吞吐量，通过 iostat 即可获得

通过fuse 挂载的卷，无法获取性能数据，只能通过测试工具如 fio 获得，在业务运营中，定位问题需要排除磁盘 IO 是否有问题，如果仅从业务感知上得到 IO 卡了，很难说的准一定就是 IO的问题。

Prometheus 没看到或者不够直观的能看到，关于fuse client 的面板我看的不是很懂而且也没有数据，fuse client 已经配置上报。

**Comment by awzhgw** [comment]
@zcola  it is a good idea.. we will add iops metrics to fuse client
