### ISSUE TITLE
无法下线meta，data无法启动

### ISSUE THREAD

**Issue by sxb12345** [chubaofs/chubaofs#504]
[root@localhost ~]# curl -v "http://172.28.168.154:17010/metaPartitio/decommission?id=1&addr=172.28.168.153:17210"
* About to connect() to 172.28.168.154 port 17010 (#0)
*   Trying 172.28.168.154...
* Connected to 172.28.168.154 (172.28.168.154) port 17010 (#0)
> GET /metaPartitio/decommission?id=1&addr=172.28.168.153:17210 HTTP/1.1
> User-Agent: curl/7.29.0
> Host: 172.28.168.154:17010
> Accept: */*
> 
< HTTP/1.1 404 Not Found
< Content-Type: text/plain; charset=utf-8
< X-Content-Type-Options: nosniff
< Date: Fri, 17 Apr 2020 11:13:09 GMT
< Content-Length: 19
< 
404 page not found
* Connection #0 to host 172.28.168.154 left intact
[root@localhost ~]# curl -v "http://172.28.168.154:17010/metaPartitio/decommission?id=1&addr=172.28.168.154:17210"
* About to connect() to 172.28.168.154 port 17010 (#0)
*   Trying 172.28.168.154...
* Connected to 172.28.168.154 (172.28.168.154) port 17010 (#0)
> GET /metaPartitio/decommission?id=1&addr=172.28.168.154:17210 HTTP/1.1
> User-Agent: curl/7.29.0
> Host: 172.28.168.154:17010
> Accept: */*
> 
< HTTP/1.1 404 Not Found
< Content-Type: text/plain; charset=utf-8
< X-Content-Type-Options: nosniff
< Date: Fri, 17 Apr 2020 11:13:20 GMT
< Content-Length: 19
< 
404 page not found
* Connection #0 to host 172.28.168.154 left intact
[root@localhost ~]# curl -v "http://172.28.168.154:17010/metaPartitio/decommission?id=1&addr=172.28.168.225:17210"
* About to connect() to 172.28.168.154 port 17010 (#0)
*   Trying 172.28.168.154...
* Connected to 172.28.168.154 (172.28.168.154) port 17010 (#0)
> GET /metaPartitio/decommission?id=1&addr=172.28.168.225:17210 HTTP/1.1
> User-Agent: curl/7.29.0
> Host: 172.28.168.154:17010
> Accept: */*
> 
< HTTP/1.1 404 Not Found
< Content-Type: text/plain; charset=utf-8
< X-Content-Type-Options: nosniff
< Date: Fri, 17 Apr 2020 11:13:26 GMT
< Content-Length: 19
< 
404 page not found
* Connection #0 to host 172.28.168.154 left intact
[root@localhost ~]# curl -v "http://172.28.168.154:17010/metaPartitio/decommission?id=1&addr=172.28.168.225:17210"

**Comment by awzhgw** [comment]
@sxb12345   the right url is  /metaPartition/decommission?id=1&addr=172.28.168.153:17210
