### ISSUE TITLE
 cfs-cli cluster info 不可用，无法指定本地master

### ISSUE THREAD

**Issue by bingoku** [chubaofs/chubaofs#506]
![image](https://user-images.githubusercontent.com/4134788/79629496-da807180-817c-11ea-921b-f7ca00a28423.png)

**Comment by mervinkid** [comment]
Hi, @bingoku 
Thanks for your feedback.
The CLI tool will automatically create a hidden file named `.cfs-cli.json` in your home directory with the following content:
```json
{
  "masterAddr": [
    "master.chubao.io"
  ]
}
```
Specify the master address of your cluster for the CLI tool in this configuration file.
The documentation on the CLI tool is not yet complete, and the functions currently provided by the CLI tool are relatively simple.

We will add an easier-to-use initial configuration process to the CLI and add more functions to it.

**Comment by bingoku** [comment]
> Hi, @bingoku
> Thanks for your feedback.
> The CLI tool will automatically create a hidden file named `.cfs-cli.json` under your home directory with the following content:
> 
> ```json
> {
>   "masterAddr": [
>     "master.chubao.io"
>   ]
> }
> ```
> z
> Specify the master address of your cluster for the CLI tool in this configuration file.
> The documentation on the CLI tool is not yet complete, and the functions currently provided by the CLI tool are relatively simple.
> 
> We will add an easier-to-use initial configuration process to the CLI and add more functions to it.
