### ISSUE TITLE
数据节点网络流量不均衡

### ISSUE THREAD

**Issue by biuboombiuboom** [chubaofs/chubaofs#592]
环境描述
4台数据节点和元数据节点混合部署
万兆网卡

测试case 顺序读
block size  1m 
文件大小 1g
两个客户端 每个客户端80个进程  累计160个线程
测试脚本
/usr/local/bin/fio -directory=/data/cfs/mountpoint -ioengine=libaio -iodepth=4 -numjobs=80 -thread=1 -rw=read -blocksize=1m -size=1g -name=singleFile -direct=1 -group_reporting=1 -fallocate=none -time_based=1 -runtime=120 

现象描述
其中一台的出口网络达到瓶颈的情况下，其余三台出口流量使用均在25%左右
![image](https://user-images.githubusercontent.com/7258606/83098638-c580f180-a0dd-11ea-9414-1625cdb25d28.png)

是否是因为dataPartition的leader在数据节点之间分布不均匀导致了这种现象？ 如果是，是否有改进计划

**Comment by mervinkid** [comment]
Hi @biuboombiuboom 
Thanks for your feedback.
What are the parameters for creating the volume? 
For example, whether the `FollowerReader` option is enabled.

**Comment by biuboombiuboom** [comment]
>  @biuboombiuboom 
感谢回复

curl -v "http://172.24.64.74:17010/admin/createVol?name=test&capacity=2000&owner=cfs" 
其余为默认配置，看文档FollowerReader应该是false

**Comment by mervinkid** [comment]
When scheduling resources, the Master has the concept and logic of NodeSet to prevent heartbeat burst. The current uneven traffic can also be related to NodeSet.

Enabling the `FollowerRead` option can improve the balance of traffic and improve read throughput.

When the `FollowerRead` option is enabled, it will allow reading data from non-Leader data partitions. It can improve the throughput of read operations.

ChubaoFS uses two replication protocols, primary-backup replication and Raft. 
The primary-backup replication is used for append writing, and Raft is used for overwriting.

Enabling the `FollowerRead` option allows for both performance and consistency in the append writing. But in the presence of an overwrite scenario, some consistency will be lost.

**Comment by biuboombiuboom** [comment]
读和写的数据流都是client和leader之间的，打开follwerRead可能会缓减读的流量问题（尚未验证），可是对于写操作应该会和写有同样的问题

**Comment by biuboombiuboom** [comment]
打开 followerRead 之后 
![image](https://user-images.githubusercontent.com/7258606/83397736-b200be00-a430-11ea-92a0-0e3110ad638b.png)
情况没有什么改善
@mervinkid 有微信群或者QQ群吗？

**Comment by mervinkid** [comment]
We have a community WeChat group. 
Here is the QR code.
![WechatIMG1](https://user-images.githubusercontent.com/5708406/83493844-fa2ee780-a4e7-11ea-91c3-eefd8e0552fd.jpeg)

>Notes: 
>This QR code will expire after June 9, 2020 Beijing time.

**Comment by awzhgw** [comment]
@biuboombiuboom 建议多创建一些dataPartition

**Comment by awzhgw** [comment]
@biuboombiuboom  是不是每个dataNode的磁盘容量不一样导致的？？？

**Comment by biuboombiuboom** [comment]
@awzhgw 4台数据节点的物理配置是一样的
4台数据节点，每台8块数据盘，每块盘960G

**Comment by Victor1319** [comment]
@biuboombiuboom your problem have been resolved? if not, please provide try to use latest version
