### ISSUE TITLE
监控图表没有数据

### ISSUE THREAD

**Issue by biuboombiuboom** [chubaofs/chubaofs#602]
按照文档部署的监控，dashboard部分面板没有数据
![image](https://user-images.githubusercontent.com/7258606/83506381-b2b15700-a4f9-11ea-8910-4872311e825e.png)
![image](https://user-images.githubusercontent.com/7258606/83506485-d6749d00-a4f9-11ea-9f70-3d9c7359b455.png)
prometheus relabel_configs配置
- source_labels: ['__meta_consul_tags']
      regex: (?:,app=)(.*?)(?:,role=.*)
      target_label: app
    - source_labels: ['__meta_consul_tags']
      regex: (?:,app=.*?,role=)(.*)(?:,cluster=.*)
      target_label: role
    - source_labels: ['__meta_consul_tags']
      regex: (?:,app=)(.*)(?:,role=)(.*)(?:,cluster=)(.*)(?:,)
      target_label: cluster
      replacement: $3
      action: replace

**Comment by ZhuZhengyi** [comment]
没有数据的图表是因为该图表的指标所在的函数还没有执行，所以没有触发对应的指标数据采集，可以进行各种读写，删除操作再看一下

**Comment by biuboombiuboom** [comment]
测试了文件新建 删除 ，新建卷操作 ，依然没有指标数据

**Comment by ZhuZhengyi** [comment]
有可能有些版本的监控面板指标和源码中的指标名称没有完全同步，可以在http://<datanode_ip>:<exporterPort>/metrics中看一下所有指标，没有的可以在grafana面板临时删除，也可以使用最新版本试下
