### ISSUE TITLE
Feature request: 希望可以提供元数据内存需求模型

### ISSUE THREAD

**Issue by vnline** [chubaofs/chubaofs#615]
从当前测试结果来看，大量小文件消耗较大量内存。无法判断增长规模情况。希望可以提供文件元数据需求内存计算模型，以便更好规划元数据资源，规划集群容量。

**Comment by awzhgw** [comment]
@vnline  it is a good idea.....We will provide related help in our document

**Comment by mervinkid** [comment]
ACK and WIP.
