### ISSUE TITLE
metanode logger error  "file corrupted" and cpu high usage

### ISSUE THREAD

**Issue by zcola** [chubaofs/chubaofs#617]
**Describe the bug**
```
2020/06/05 06:09:59.458757 [ERROR] partition_delete_extents.go:187: [deleteExtentsFromList] partitionId=173, EXTENT_DEL_65 file corrupted!
```
cpu high usage

**Environment**
Describe your server system version, kernel version

**To Reproduce**

**Expected behavior**

**Additional context**

**Comment by awzhgw** [comment]
@zcola  we will fix it
