### ISSUE TITLE
垃圾元数据加载问题

### ISSUE THREAD

**Issue by vnline** [chubaofs/chubaofs#622]
节点下线元数据后节点残留元数据分片数据，重启元数据节点会加载残留元数据垃圾数据，导致元数据节点内存占用较高。

版本：master版本

重现步骤:
下线较大量元数据分片后

建议：
仅加载现有该节点有心跳的元数据分片，减少内存占用。同时清理残留垃圾元数据分片。日志记录清理元数据ID。

**Comment by awzhgw** [comment]
@vnline  we will fix it on today.

**Comment by awzhgw** [comment]
@vnline  it has fixed .. i will close this issue
