### ISSUE TITLE
关于数据分片的一些疑问

### ISSUE THREAD

**Issue by biuboombiuboom** [chubaofs/chubaofs#625]
两个容量均为2000G的卷,test和test1
![image](https://user-images.githubusercontent.com/7258606/84007499-1c6eac80-a9a3-11ea-9d2d-f7813c9eb8a4.png)
**test**的数据分片数量369
![image](https://user-images.githubusercontent.com/7258606/84009254-943dd680-a9a5-11ea-9023-05b1023a0868.png)
**test1**的数据分片数量39
![image](https://user-images.githubusercontent.com/7258606/84009399-c51e0b80-a9a5-11ea-9734-10ded3aba6eb.png)

未在集群中手动执行过数据分片的创建命令。
疑问：
默认不是10个分片吗？是集群进行了自动扩展吗？如果是，那么数据分片的扩张依据和逻辑是什么？

**Comment by zhuhyc** [comment]
@biuboombiuboom  Yes, create 10 data partitions by default. The master module has a worker  which executes expansion task every two minutes, meet any of the following conditions, the master will automatically perform the task of creating data partitions.
1. the capacity of a vol larger than 200TB,and the num of writable data partitions less than 200
2. the num of writable data partitions less than 10

the test1 will  also automatically create data partitions,you can check it.

**Comment by biuboombiuboom** [comment]
1.两个卷的容量均未超过200T 第一条不满足 pass
2.那就是说 在某次可用分片检测中发现可写的数据分片数量小于10 然后执行了扩展
这里有新的疑问？数据分片状态转移的逻辑是什么呢？

**Comment by zhuhyc** [comment]
1.The status of the data partition is reported by the datanode. The master checks whether the three replicas(default) are writable. If any one is not writable, the status of the data partition is set to readonly
2. In order to ensure that the vol is writable, as long as the usage does not exceed the capacity and the writable data partitions are less than 10, it will continue to expand

**Comment by biuboombiuboom** [comment]
测试发现 当数据分片大小设为10G时，会不停的创建数据分片，感觉时一个bug

**Comment by zhuhyc** [comment]
If the capacity of a vol is too small, the used size reported by datanode will easily larger than the capacity of the vol, the status of all data partitions will be set to readonly, then it will expand to create new data partitions. If we don't expand to create data partitions, the vol will not writable. In a word,don't set the capacity of a vol too small

**Comment by biuboombiuboom** [comment]
卷的容量1000G 
![image](https://user-images.githubusercontent.com/7258606/84220143-b9952680-ab04-11ea-9de4-18310628cd2f.png)
所以不是卷容量太小导致的

**Comment by zhuhyc** [comment]
There is a scenario where the client internally replaces the write data and delete data temporarily, resulting in the partition's state being writable for a while, and then changed to readonly again. To reduce the impact of this situation on the client if the writable space of the partition  is less than 10GB, set the status of the partition to be readonly in advance. So if your partition size is 10GB,the status of partition will be always readonly

**Comment by biuboombiuboom** [comment]
卷创建完，客户端还有没有进行过挂载，所以这个场景我不是很理解
测试发现数据分片<=10G时 就会有这个问题，是否需要把这个临界指放入文档或者配置约束中

**Comment by zhuhyc** [comment]
Thank you very much. We accept your suggestion. We will check the size of data partition, if size less than 30GB, creating vol will be failed with a error of size is too small,the documentation also explains this.
