### ISSUE TITLE
Metanodes not wirtable, can't understand the reason

### ISSUE THREAD

**Issue by netdata-be** [chubaofs/chubaofs#673]
Hi there,

We are working on integrating chuboafs as our storrage.

Since yesterday I get meta nodes who are unwritable.

```
cli metanode list
Master address: [cfs-master.service.consul:17010]
[Meta nodes]
ID        ADDRESS               WRITABLE    STATUS
3         192.168.44.12:17210    No          Active
5         192.168.44.10:17210    Yes         Active
6         192.168.44.11:17210    No          Active
```

If I stop all nodes and start them again they becore writable for a couple of minutes.

In the logs I can find this:

```
2020/06/19 13:06:10.139372 [WARN ] cluster_task.go:879: mpId[12],start[16777217],end[33554432],addr[192.168.44.11:17210],used[465690624]
2020/06/19 13:06:10.139376 [ERROR] cluster_task.go:881: mp[12] is not the last meta partition[13]
```

What could be the reason? 
And how to solve this?

Attached is the full log 

[logs_all_nodes_sorted.log](https://github.com/chubaofs/chubaofs/files/4805086/logs_all_nodes_sorted.log)

**Comment by awzhgw** [comment]
@netdata-be  your metanode.cfg totalMem set too slow,   it must > 4GB

**Comment by mervinkid** [comment]
@netdata-be 

For performance reasons, the metadata will be fully loaded into memory, and the` totalMem` configuration is introduced to set the memory threshold that the MetaNode process can use. 

When the memory available to the MetaNode reaches this threshold, the Metanode will become to read-only status.

It is recommended to configure `totalMem` to be greater than 4GB.

**Comment by netdata-be** [comment]
Hi all, thanks for the info.
That seems to solve it.

What about the error message:
```
2020/06/19 13:06:10.139372 [WARN ] cluster_task.go:879: mpId[12],start[16777217],end[33554432],addr[192.168.44.11:17210],used[465690624]
2020/06/19 13:06:10.139376 [ERROR] cluster_task.go:881: mp[12] is not the last meta partition[13]
```

Is that a consequence of being read-only?

**Comment by mervinkid** [comment]
@netdata-be 

Which version are you using?

You can use the "-v" argument to get version information.
```shell
$ cfs-server -v
```

**Comment by netdata-be** [comment]
I'm running the docker image: `chubaofs/cfs-server:2.0.2`

Which results to:
```
ChubaoFS Server
Branch: master
Commit: 35a0c6dedc435b244a0980cdf3e11f9c6755a038
Build: go1.13.6 linux amd64 2020-04-28 07:00
```

**Comment by zhuhyc** [comment]
@netdata-be  You can ignore the error message, it just hint the metapartition to be splited is not the max meta partition. When meta node reaches the threshold, we will split only the meta partition which is the max meta partition, we record a error messge to log occurred any error. We can refine the log message in the next version.
