### ISSUE TITLE
Master exporterPort无法获取监控信息

### ISSUE THREAD

**Issue by tomqijianbo** [chubaofs/chubaofs#687]
Version: Pre-release-v2.1
Description:
Master启动后，Master exporterPort无法获取监控信息。使用V2.0.0可以正常监听端口

**Comment by ZhuZhengyi** [comment]
master exporter use http listen port for export to rerouter leader master.

**Comment by tomqijianbo** [comment]
![image](https://user-images.githubusercontent.com/42462349/85483579-abacce80-b5f7-11ea-9172-32b936e02560.png)
All the master nodes can't get the monitor informations for prometheus, but the the meta node and data node work fine.
It is only reproduced in Pre-release-v2.1.

**Comment by ZhuZhengyi** [comment]
> ![image](https://user-images.githubusercontent.com/42462349/85483579-abacce80-b5f7-11ea-9172-32b936e02560.png)
> All the master nodes can't get the monitor informations for prometheus, but the the meta node and data node work fine.
> It is only reproduced in Pre-release-v2.1.

master exporter used listen port after release v2.1, the exporterPort is kept to compatible with old version

**Comment by mervinkid** [comment]
@tomqijianbo 

Starting from version `2.1.0-rc.1` which you are using, the monitoring port of the Master has been merged with its main service port, which is the port configured by `listen`. 
The `prodPort` configuration in Master have been invalid.

**Comment by tomqijianbo** [comment]
ok, got it.

**Comment by Zorlin** [comment]
We should update the docs to reflect this... I wasted hours tonight trying to figure out why exporterPort didn't work on the master.
