### ISSUE TITLE
各位好，请问如何删除旧的，如何更新

### ISSUE THREAD

**Issue by sxb12345** [chubaofs/chubaofs#689]
问题1：各位好，请问如何删除旧的，如何升级？
问题2：如果我要监控，不太会配置，求助

**Comment by mervinkid** [comment]
@sxb12345 

**For question 1:**
Up to now `v2.1.0-rc.1` version is compatible with the old version data. (If it is not compatible, it will be explained in the release version). You can use the following steps to upgrade:
1. Exit the old version.
2. Replace the binary with the new version.
3. Start the new version.

If you want your business to be affected as little as possible, you can use a rolling upgrade.

**For question 2:**
To use Prometheus to monitor ChubaoFS, you need to perform the following steps:
1. Make sure consol is deployed in your environment. Prometheus uses consol for registration and discovery.
2. Configure the `exporterPort` and `consulAddr` configuration in the configuration file of each node.

The `exporterPort` is used to set the service port for Prometheus to pull monitoring data for the current node.
The `consulAddr` is used to configure the address of consol service.

Example:
```json
{
    "exporterPort": 9505,
    "consulAddr": "http://consul.prometheus-cfs.local"
}
```

Notes:
>Since `v2.1.0-rc.1`, the Master's `exportPort` configuration has been merged with its main service port configuration `listen`.
> Detail see issue #687 .

**Reference:**
[Monitor — ChubaoFS documentation](https://chubaofs.readthedocs.io/en/latest/user-guide/monitor.html)

**Comment by awzhgw** [comment]
@sxb12345  直接删除你的配置文件中的所有的目录，并把安装目录删除即可。。然后你可以直接使用yum来安装
