### ISSUE TITLE
datanode磁盘空间占满，日志巨大

### ISSUE THREAD

**Issue by sxb12345** [chubaofs/chubaofs#690]
8.1G	./logs
不知道啥原因？
导致系统无法创建目录

**Comment by mervinkid** [comment]
@sxb12345 

What is the log level you configured？

**Comment by sxb12345** [comment]
很多，占了几G，把系统的给占满了
raft_debug.log.2020-04-17  raft_info.log.2020-04-17
raft_debug.log.2020-04-18  raft_info.log.2020-04-18

**Comment by mervinkid** [comment]
The amount of logs at the info and debug levels is very large. Unless otherwise required in the production environment, it is recommended to configure the error level.
