### ISSUE TITLE
Erasure coding support for cold data

### ISSUE THREAD

**Issue by mervinkid** [chubaofs/chubaofs#700]
By storing the data with erasure coding, the storage cost of cold data can be greatly reduced, and the conversion between the copy and erasure coding of the cold and hot data is automatically performed by the asynchronous task in the background.

**Comment by mervinkid** [comment]
**Demands of erasure coding:**
1. Support duplicate partition and erasure coding partition in the same volume.
2. Support automatic data migration (in the early stage, only the data writing situation was used as the basis for judging cold data and hot data).
    - Support cold data automatic migration from replicate partition to erasure coding partition.
    - ~~Support automatic migration of hot data from erasure coding partition to replicate partition.~~
3. Support the client to read data directly from erasure coding partition.
4. ~~Support to modify the data that has been migrated.~~
    - ~~Support additional write to the data that has been migrated.~~
        1. ~~The added content is saved as replicate data.~~
        2. ~~The added content is saved as erasure coding data.~~
    - ~~Support to modify and write the migrated data.~~
        1. ~~The modified content is saved as replicate data.~~
        2. ~~Save the modified content as erasure coding data.~~

**Comment by mervinkid** [comment]
**Requirements of erasure coding:**
1. Avoid the modification of the data structure of the data that has been persisted, and avoid the compatibility problems of the data that has been persisted.
2. The data reading interface after EC encoding is consistent with that before EC encoding to avoid client compatibility issues.
3. Consider the coexistence of new and old versions that may appear during the online process to avoid data conflicts.
4. Decoupling codec related logic.

**Comment by Victor1319** [comment]
@mervinkid it will be supported in the future, WIP
