### ISSUE TITLE
rsync 同步文件同一文件无法校验跳过

### ISSUE THREAD

**Issue by vnline** [chubaofs/chubaofs#707]
**Describe the bug**
使用rsync -azvP参数进行同步文件时，对同一文件（MD5一致）无法正常跳过校验，重复同步。

**Environment**
Describe your server system version, kernel version

**To Reproduce**

**Expected behavior**

**Additional context**

**Comment by mervinkid** [comment]
@vnline 

You can use the `-u` flag to skip.

```
$ rsync -h
...
-u, --update                skip files that are newer on the receiver
...
```

**Comment by yinlei-jinan** [comment]
This issue caused by ChubaoFS does not support modify inode's ModifyTime through setAttr. We have solve this issue by commit  3a569d7b9801f3a837687c474e9e0fb174e89e4f.
