### ISSUE TITLE
Got "discard message" error cause "recv channel" is too small in raft proto

### ISSUE THREAD

**Issue by ssscottt** [chubaofs/chubaofs#719]
We found that all replicas are `not available` of a metapartition, and there is no leader. We've found lots of `discard message` logs. It was because the pool of `recv channel` is too small in raft proto. When the pool was full, it discards the messages directively.

Making `ReqBufferSize` configurable with a default value 4096 is helpful.

**Comment by Victor1319** [comment]
@ssscottt please provide more expception log in your case
