### ISSUE TITLE
The footer on the docs site obscures content

### ISSUE THREAD

**Issue by jean** [chubaofs/chubaofs#742]
**Describe the bug**
The footer on the docs site obscures content

**Environment**
Firefox on Linux Mint

**To Reproduce**
- Browse to http://chubao.io/docs/
- Click on e.g. _Introduction_
- Scroll down. Notice that the last line is obscured, and the scrollbar shows that we are at the bottom of the page. 

![image](https://user-images.githubusercontent.com/84800/86884430-bef28a80-c11d-11ea-93f0-887a8401ab30.png)

**Expected behavior**
When we scroll to the bottom of the page, all content should be visible. 

**Additional context**
This does not always happen. E.g. if I ctrl-R reload a page, I can scroll all the way down and see the content successfully. 
![image](https://user-images.githubusercontent.com/84800/86884680-18f35000-c11e-11ea-81ba-fe03a3c583b1.png)

**Comment by awzhgw** [comment]
@jean https://chubaofs.readthedocs.io/en/latest/  use this doc addr

**Comment by jean** [comment]
@awzhgw maybe update the docs links on the website to use that doc addr then?
