### ISSUE TITLE
doStreamFixTinyDeleteRecord Delete PartitionID导致系统资源占用过高

### ISSUE THREAD

**Issue by wjrenren** [chubaofs/chubaofs#787]
doStreamFixTinyDeleteRecord Delete PartitionID导致系统资源占用过高，从监控上看24小时会执行一次。希望能优化一下。

系统资源
![image](https://user-images.githubusercontent.com/68722486/88359354-eb0c3d80-cda4-11ea-9b67-81319296acc2.png)

dataNode_info.log  
![image](https://user-images.githubusercontent.com/68722486/88359407-142cce00-cda5-11ea-96e9-9e01ca3137a9.png)

**Comment by mervinkid** [comment]
ACK and WIP.

Thx for your feedback.
