### ISSUE TITLE
console 试用体验

### ISSUE THREAD

**Issue by wjrenren** [chubaofs/chubaofs#802]
cfs 提供控制台是一大特色，试用了一下最新版的console希望能改善几个地方。
1、serverlist 缺少字段过滤和排序功能，有时候想看看dp最多的机器现在无法实现。
2、alarm 里也缺少分类，需要知道哪些是master报警，哪些是datanode、metanode，是否是重要的日志信息。
3、ServerManagement 下线的磁盘和服务器需要有归档可以查看。能不能显示坏的磁盘，或者在serverlist能体现磁盘个数（例如10/12可用磁盘）。
4、Volume Management  希望能看到dp分配情况。 目录数、文件数、以及是否有坏的文件，丢失的文件，提供给用户更多视角了解vol信息。

**Comment by ansjsun** [comment]
感谢您的反馈。

------------------

1、serverlist 缺少字段过滤和排序功能，有时候想看看dp最多的机器现在无法实现。
* 过滤的功能是有的， 排序功能我们需要想想哈
![image](https://user-images.githubusercontent.com/1221947/88996160-236cc800-d31f-11ea-8781-c6d919f127a5.png)

------------------

2、alarm 里也缺少分类，需要知道哪些是master报警，哪些是datanode、metanode，是否是重要的日志信息。
* alarm 是很重要的一个模块。我们现在做的还很粗糙。后期会想办法细化功能，提供更好的用户体验

3、ServerManagement 下线的磁盘和服务器需要有归档可以查看。能不能显示坏的磁盘，或者在serverlist能体现磁盘个数（例如10/12可用磁盘）。

* 这个可以考虑

------------------

4、Volume Management 希望能看到dp分配情况。 目录数、文件数、以及是否有坏的文件，丢失的文件，提供给用户更多视角了解vol信息。

* 这个实现起来可能会有难度。但是目录数和文件数可以考虑。不过可能性能代价 很高。
