### ISSUE TITLE
Require ARM64 docker images to add ARM64 job in travis

### ISSUE THREAD

**Issue by odidev** [chubaofs/chubaofs#804]
I am working on adding an ARM64 job in Travis. ARM64 job is failing as docker image `chubaofs/cfs-base:1.1` is not available for arm64.

Please check https://travis-ci.org/github/odidev/chubaofs/jobs/713238554 for the same.

I have built ARM64 binaries in ARM64 platform using below steps:

- Removed **-Werror** flag from rocksdb Makefile as deprecated warnings are being treated as errors.
- Installed libbz2-dev libsnappy-dev librocksdb-dev
- make

Binaries are created in build/bin
```
ls build/bin/
cfs-authtool cfs-cli cfs-client cfs-server
```
It will be very helpful if chubaofs docker images are available for arm64.

Please let me know if any help is required.

**Comment by mervinkid** [comment]
@odidev 

Thanks for your feedback.

At present, we have just completed the adaptation of the project compilation on the ARM platform through PR#779.

We plan to optimize the docker images.

The current design provides two images on x86 and ARM platforms each. 

- One is the basic image used to support CI testing, which will contain all dependent environments required for CI testing but does not contain ChubaoFS binary programs. 
- The other is the release image of the project, which will contain the necessary dependencies of the program and the binary program of the specified version of ChubaoFS.

Would you like to help us complete the ARM platform docker image?

**Comment by odidev** [comment]
@mervinkid,

Thanks for the reply.

Yes, I am very much happy to help. Just can you please elaborate on what kind of help you are looking into?

**Suggestion:** I think we can add steps to deploy images to Docker hub in Travis-CI.

**Comment by odidev** [comment]
As mentioned in https://github.com/chubaofs/chubaofs/issues/804#issue-668669628, I had to remove **-Werror** flag for resolving deprecated errors faced while building rocksdb on arm64 platform. It can be resolved if we upgrade rocksdb from 5.9.2 to 6.11.4.

It will be very helpful if it is upgraded. Can I raise PR for the same?

**Comment by mervinkid** [comment]
@odidev 

Sorry for reply you too late cause it is too busy in the past week.

As mentioned:

>As mentioned in #804 (comment), I had to remove -Werror flag for resolving deprecated errors faced while building rocksdb on arm64 platform. It can be resolved if we upgrade rocksdb from 5.9.2 to 6.11.4.
>It will be very helpful if it is upgraded. Can I raise PR for the same?

We think your proposal is necessary, but there is one point to note: 
- upgrading the version of gocksdb may prevent the ChubaoFS currently deployed in the production environment from being able to upgrade smoothly with low risk.  These environments are all on the x86 platform.

Hope to have a more compatible solution.
