### ISSUE TITLE
console未提供ZoneName选项导致创建报错

### ISSUE THREAD

**Issue by vnline** [chubaofs/chubaofs#805]
由于CFS参数配置了zonename别名，而console volume创建未提供zonename选项提交创建时报错，请添加zonename参数选项，谢谢！

**Comment by mervinkid** [comment]
@vnline 

ACK & WIP.

**Comment by mervinkid** [comment]
@vnline 

This issue have been fixed by the pull request #822 which have been applied and merged into `master` branch.
