### ISSUE TITLE
Token权限认证功能无效

### ISSUE THREAD

**Issue by vnline** [chubaofs/chubaofs#819]
volume添加Token认证，TokenType为2，读写模式，并开启enableToken。客户端配置中添加或不添加token参数均可挂载并读写。

**Comment by vnline** [comment]
cfs-client version:
ChubaoFS Client
Branch: originmaster
Commit: 65bca2ccfece90af49e089aff5c1048a521890

**Comment by mervinkid** [comment]
ACK and WIP.
