### ISSUE TITLE
Bug report

### ISSUE THREAD

**Issue by johnkhor0216** [chubaofs/chubaofs#839]
**Describe the bug**
Run docker/run_docker.sh -r -d /data/disk returns error shown in the ppic
![1](https://user-images.githubusercontent.com/33027184/90412314-8c09c200-e0df-11ea-8e43-640510a1a8c9.png)

**Environment**
Docker Windows 10(Home Edition), Docker 19.03.12

**Comment by hooklee2000** [comment]
Maybe you can try to config git :

**Comment by johnyii0216** [comment]
Not working.. Still getting the same error. I'm using Git Bash btw

**Comment by awzhgw** [comment]
@hooklee2000  It is recommended to use centos7

**Comment by mervinkid** [comment]
The `run_docker.sh` script have not been tested in windows platform.
