### ISSUE TITLE
支持块存储么

### ISSUE THREAD

**Issue by showsmall** [chubaofs/chubaofs#845]
支持块存储么

**Comment by awzhgw** [comment]
@showsmall  
Sorry, it is currently not supported

**Comment by showsmall** [comment]
Are there plans to support block storage in the future?

**Comment by mervinkid** [comment]
A virtual machine generally uses a block storage device that does not include a file system, and in a virtual machine scenario, multiple computing nodes do not use the same block storage device at the same time.

The applicable scenario of the distributed file system is the high-performance sharing of massive data.
