### ISSUE TITLE
build.sh failed to make again when last make failed

### ISSUE THREAD

**Issue by wsj0000** [chubaofs/chubaofs#872]
There are two issues found when compiling from code.
When downloading any file failed to vendor/dep, the make command will always failed except removing the /vender/dep folder manually.
![image](https://user-images.githubusercontent.com/11285030/91934810-d49bbf00-ed1e-11ea-9f91-1eb5a7c15888.png)
```
# wget compress dep 
get_rocksdb_compress_dep() {

   ################################################################
   ## Might check the dep files each in individual 'if' block    ##
   ################################################################
    if [ ! -d "${RootPath}/vendor/dep" ]; then
        mkdir -p ${RootPath}/vendor/dep
        cd ${RootPath}/vendor/dep
        wget http://www.zlib.net/zlib-1.2.11.tar.gz
        wget --no-check-certificate https://astuteinternet.dl.sourceforge.net/project/bzip2/bzip2-1.0.6.tar.gz
        wget https://codeload.github.com/facebook/zstd/zip/v1.4.5
        wget https://codeload.github.com/lz4/lz4/tar.gz/v1.9.2

        tar zxf zlib-1.2.11.tar.gz
        tar zxf bzip2-1.0.6.tar.gz
        unzip v1.4.5
        tar zxf v1.9.2

        #rm -rf zlib-1.2.11.tar.gz bzip2-1.0.6.tar.gz v1.4.5 v1.9.2
        cd ${RootPath}
        
    fi
    cd ${RootPath}

}

```
And astuteinternet.dl.sourceforge.net's certificate maybe has expired already. ```--no-check-certificate``` needed for ```wget``` command.
![image](https://user-images.githubusercontent.com/11285030/91934638-753daf00-ed1e-11ea-87a9-1e52d6ec4207.png)
Success download after add ```--no-check-certificate```
![image](https://user-images.githubusercontent.com/11285030/91935245-de71f200-ed1f-11ea-8c82-c37a5d872242.png)

**Comment by hooklee2000** [comment]
Thanks，I will fix it .
