### ISSUE TITLE
Unit wrong in Console->ServerList 

### ISSUE THREAD

**Issue by wsj0000** [chubaofs/chubaofs#878]
![image](https://user-images.githubusercontent.com/11285030/91973236-7e467480-ed4e-11ea-839b-b76371d4aa7f.png)
![image](https://user-images.githubusercontent.com/11285030/91973259-88687300-ed4e-11ea-8ac1-2509561df1a3.png)

**Comment by mervinkid** [comment]
ACK.

**Comment by ansjsun** [comment]
received and repaired as soon as possible
