### ISSUE TITLE
[Feature request] Auto scaling policy for volume capacity

### ISSUE THREAD

**Issue by wsj0000** [chubaofs/chubaofs#880]
- When the volume reach the a certain percent of usage (80% maybe), and the DNs for the volume also have the enough space for the volume to double up the capacity, the scaling will be trigger. Shrink policy is similar.
- Auto scaling might be optional. Fixed capacity should still be keep for some volume.

Just for discuss.

**Comment by jadewang198510** [comment]
you can  use cli-tool/api to do this job by monitoring
