### ISSUE TITLE
Volume cannot be recreate as the same name before physical deletion complete

### ISSUE THREAD

**Issue by wsj0000** [chubaofs/chubaofs#881]
![image](https://user-images.githubusercontent.com/11285030/92074285-48ee6500-ede8-11ea-8c16-3288175d14c3.png)
Volume 'Marked delete' taking to much time and cannot be recreate by the same name before physical deletion complete. (Marked delete status has already been keep in 20 mins)
Here is the log in leader master
![image](https://user-images.githubusercontent.com/11285030/92075946-1a728900-edec-11ea-85bf-ed8a14462d41.png)

Truncate data is a common case. There should be a way to handle this.

Version: Build from master (commit b9c92b4)

**Comment by mervinkid** [comment]
The current design logic is to mark the deleted volume, and then asynchronously clean up related resources and release space. 
These resources include MetaPartition, DataPartition, and the disk space they occupy. 
There are more resources that need to be released, the release process is relatively long, and it is necessary to ensure that all resources are released.

**Comment by wsj0000** [comment]
> The current design logic is to mark the deleted volume, and then asynchronously clean up related resources and release space.
> These resources include MetaPartition, DataPartition, and the disk space they occupy.
> There are more resources that need to be released, the release process is relatively long, and it is necessary to ensure that all resources are released.

Is it possible that mark the relative resources as ```Pending Delete``` instead of marking the whole Volume as 'Marked Delete' to waiting all resources to be released. When all relative resources have be marked as ```Pending Delete```, the Volume can be treat as ```Deleted```. Push all relative resources to a 'Pending Delete List' should be quick.
