### ISSUE TITLE
Read amplification? cfs-client fileread_count gt  real  read count 

### ISSUE THREAD

**Issue by biuboombiuboom** [chubaofs/chubaofs#882]
# cfs version:
ChubaoFS Server
Branch: heads/v2.1.0
Version: 2.1.0
Commit: 53ef123840bfce4bfd69058ac2a169fcd8b4a18c
Build: go1.14.2 linux amd64 2020-07-17 15:35

# kernel：
Linux version 3.10.0-1062.18.1.el7.x86_64

# case:
file count: 100
file size: 1GB
goroutine: 20
read 128KB at a time
lasting 1 minute.

# my statistical: 
goroutine:0,read count:1201,time:60028124757 ,max:488244144 
goroutine:1,read count:1214,time:60019489336 ,max:380531654 
goroutine:2,read count:1215,time:60004452234 ,max:498780539 
goroutine:3,read count:1209,time:60029252868 ,max:581194955 
goroutine:4,read count:1234,time:60011920351 ,max:461537583 
goroutine:5,read count:1267,time:60007164362 ,max:365917386 
goroutine:6,read count:1212,time:60002864167 ,max:503120270 
goroutine:7,read count:1277,time:60041189955 ,max:376534673 
goroutine:8,read count:1255,time:60019658896 ,max:547613830 
goroutine:9,read count:1219,time:60015853207 ,max:397719604 
goroutine:10,read count:1216,time:60028374698 ,max:528057577 
goroutine:11,read count:1234,time:60002039642 ,max:602735665 
goroutine:12,read count:1211,time:60027032896 ,max:362544265 
goroutine:13,read count:1258,time:60021860382 ,max:492887507 
goroutine:14,read count:1265,time:60020571523 ,max:488969044 
goroutine:15,read count:1275,time:60040684770 ,max:329215423 
goroutine:16,read count:1202,time:60024563549 ,max:543418829 
goroutine:17,read count:1229,time:60013293018 ,max:548734015 
goroutine:18,read count:1220,time:60008668512 ,max:363759860 
goroutine:19,read count:1243,time:60005162739 ,max:329106861 

concurrence:20,total:24656,maxTime:(602735665)ns
# cfs metrics
before testing
![image](https://user-images.githubusercontent.com/7258606/92075828-e6976380-edeb-11ea-9bb4-aa91dc612b29.png)
after
![image](https://user-images.githubusercontent.com/7258606/92075783-d089a300-edeb-11ea-849f-45ffea1e5a4b.png)

111182-55791=55391

# question
fuseclient_fileread_count:55391
test count:24656

# code
```golang
package main

import (
	"fmt"
	"math/rand"
	"os"
	"path"
	"strconv"
	"sync"
	"time"
)

var rootPath = "/cfs/test"
var counter sync.Map
var timer sync.Map
var pp = 20
var stop = make(chan int, pp)
var fileSize=1024*1024*1024

type Timer struct {
	maxTime   int64
	totalTime int64
}

func main() {
	//initFile()
	var wg sync.WaitGroup
	for i := 0; i < pp; i++ {
		wg.Add(1)
		go func(i int) {
			defer wg.Done()
			randRead(i)
		}(i)
	}

	time.Sleep(1 * time.Minute)
	for i := 0; i < pp; i++ {
		stop <- i
	}
	wg.Wait()
	var total int
	var maxTime int64
	for i := 0; i < pp; i++ {
		count, _ := counter.Load(i)
		if count != nil {
			total = total + count.(int)
		}
		t, _ := timer.Load(i)
		tr := t.(*Timer)
		if tr.maxTime > maxTime {
			maxTime = tr.maxTime
		}
		fmt.Printf("goroutine:%d,read count:%d,time:%d ,max:%d \n", i, count.(int), tr.totalTime, tr.maxTime)
	}
	fmt.Printf("concurrence:%d,total:%d,maxTime:(%d)ns\n", pp, total, maxTime)

}

func read(goIndex int) {
	count:=0
	var offset int64
	fileNo:=0
	file := strconv.Itoa(fileNo)
	size := 1024 * 128
	f, err := os.OpenFile(path.Join(rootPath, file), os.O_RDWR, 777)
	if err != nil {
		panic(err)
	}
	times := make([]int64, 0)
	for {
		select {
		case <-stop:
			tr := new(Timer)
			fmt.Printf("stop goroutine: %d\n", goIndex)
			counter.Store(goIndex, count)
			var maxTime int64
			var total int64
			for i := 0; i < len(times); i++ {
				if times[i] > maxTime {
					maxTime = times[i]
				}
				total = total + times[i]
			}
			tr.maxTime = maxTime
			tr.totalTime = total
			timer.Store(goIndex, tr)
			return
		default:
			t1 := time.Now()
			data := make([]byte, size)
			n, err := f.ReadAt(data, offset)
			if err != nil {
				panic(err)
			}
			count++
			times = append(times, time.Since(t1).Nanoseconds())
			offset = offset + int64(n)
			if offset-int64(fileSize)>=0{
				f.Close()
				fileNo=fileNo+1%100
				file=strconv.Itoa(fileNo)
				offset=0
				f, err = os.OpenFile(path.Join(rootPath, file), os.O_RDWR, 777)
				if err!=nil{
					panic(err)
				}
			}

		}
	}

}

func randRead(index int) {
	count := 0
	size := 1024 * 128
	times := make([]int64, 0)
	for {
		select {
		case <-stop:
			tr := new(Timer)
			fmt.Printf("stop goroutine: %d\n", index)
			counter.Store(index, count)
			var maxTime int64
			var total int64
			for i := 0; i < len(times); i++ {
				if times[i] > maxTime {
					maxTime = times[i]
				}
				total = total + times[i]
			}
			tr.maxTime = maxTime
			tr.totalTime = total
			timer.Store(index, tr)
			return
		default:
			t1 := time.Now()

			rand.NewSource(time.Now().UnixNano())
			file := strconv.Itoa(rand.Intn(100))
			f, err := os.OpenFile(path.Join(rootPath, file), os.O_RDWR, 777)
			if err != nil {
				panic(err)
			}
			data := make([]byte, size)
			offset := rand.Int63n(int64(fileSize - 1024*129))
			_, err = f.ReadAt(data, offset)
			if err != nil {
				panic(err)
			}
			f.Close()
			count++
			times = append(times, time.Since(t1).Nanoseconds())
		}
	}
}

func initFile() {
	data := getData(fileSize)
	for i := 0; i < 100; i++ {
		fileName := strconv.Itoa(i)
		path := path.Join(rootPath, fileName)

		if _, err := os.Stat(path); err == nil {
			continue
		}
		f, err := os.Create(path)
		if err != nil {
			panic(err)
		}

		f.Write(data)
		f.Close()
	}
}

func getData(size int) (data []byte) {
	for i := 0; i < size; i++ {
		data = append(data, 'a')
	}
	return
}

```

If concurrency is reduced, the data can be matched

**Comment by mervinkid** [comment]
Hi @biuboombiuboom 

This is caused by the kernel VFS (Linux Virtual File System) for page alignment and read ahead caching.

When using the POSIX file system interface based on the fuse client, the call chain is as follows:

1. `application` (user space)
2. `syscall` (user space, like open, read, write, etc.)
3. `Kernel VFS` (kernel space)-> `fuse` (user space)
4. `ChubaoFS Fuse Client` (user space) 
5. `ChubaoFS Servers` (distributed, master, metanode, datanode).

**[Example]**

Read 128KB of data from a 128MB file at offset 15.

**1. Sample code**
```go
package main

import (
	"os"
)

func main() {
	f, err := os.OpenFile("/cfs/mnt/test", os.O_SYNC , os.ModePerm)
	defer f.Close()
	if err != nil {
		panic(err)
	}
	b := make([]byte, 1024*128)
	if _, err := f.ReadAt(b, 15); err != nil {
		panic(err)
	}
}
```

**2. Build test program**
```shell
$ go build -o rreadtest
```

**3. Execute test program**
Execute sample code and trace syscall by using `strace`. 
```shell
$ strace -f ./rreadtest &>> strace.log
```

**4. Collecting information**
Grep `pread` record from the `strace.log` you can found only one system call invoked by `rreadtest` application.
```shell
$ grep pread strace.txt
[pid   324] <... pread64 resumed> "aaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaa"..., 65536, 15) = 65536
```

Grep `RACE Read:` from ChubaoFS Client debug log you can found three record.
```shell
$ grep "RACE Read:" client_debug.log
2020/09/03 09:41:49.261373 [DEBUG] file.go:187: TRACE Read: ino(33554457) offset(0) reqsize(131072) req(Read [ID=0x22ef4 Node=0x2 Uid=0 Gid=0 Pid=304] 0x2 131072 @0x0 dir=false fl=0 lock=0 ffl=OpenReadWrite+OpenNonblock) size(131072) (1528817)ns
2020/09/03 09:41:49.262616 [DEBUG] file.go:187: TRACE Read: ino(33554457) offset(262144) reqsize(131072) req(Read [ID=0x22ef8 Node=0x2 Uid=0 Gid=0 Pid=304] 0x2 131072 @0x40000 dir=false fl=0 lock=0 ffl=OpenReadWrite+OpenNonblock) size(131072) (796239)ns
2020/09/03 09:41:49.263085 [DEBUG] file.go:187: TRACE Read: ino(33554457) offset(131072) reqsize(131072) req(Read [ID=0x22ef6 Node=0x2 Uid=0 Gid=0 Pid=304] 0x2 131072 @0x20000 dir=false fl=0 lock=0 ffl=OpenReadWrite+OpenNonblock) size(131072) (1317147)ns
```

**5.Analysis**
It can be seen that although the user mode test program only made one system call to read data from the file, which is consistent with our expectations, but there are three calls from the kernel VFS to the ChubaoFS Client.

The first two calls are to read data and perform page alignment.
The third call is for read ahead caching.
