### ISSUE TITLE
[已弃坑]Unbalanced load after repairing bad disk of DN node in test environment

### ISSUE THREAD

**Issue by zcola** [chubaofs/chubaofs#907]
test environment

4 DNs, each with 12 disks, one of which 228 is broken, and the load has been uneven after repairing.

Only 4 volumes have been continuously written. These 4 volumes correspond to the 4 write nodes of the same ES cluster, so the write traffic is basically balanced, and data is deleted regularly. It can be said that the test scenario is very simple

I don’t understand why the load of the 228 is the lowest. In some periods, only the machine with the highest load has half of the writes. The replacement hard disk basically does not have much traffic.

```
sda is the hard disk after failure replacement
/dev/sda        7.3T  2.0T  5.3T  28% /disk0
/dev/sdc        7.3T  3.2T  4.1T  44% /disk1
/dev/sdd        7.3T  3.2T  4.2T  44% /disk2
/dev/sde        7.3T  3.4T  4.0T  46% /disk3
/dev/sdf        7.3T  3.3T  4.1T  45% /disk4
/dev/sdg        7.3T  3.4T  4.0T  46% /disk5
/dev/sdh        7.3T  3.2T  4.2T  43% /disk6
/dev/sdi        7.3T  3.4T  4.0T  46% /disk7
/dev/sdj        7.3T  3.4T  3.9T  47% /disk8
/dev/sdk        7.3T  3.1T  4.2T  43% /disk9
/dev/sdl        7.3T  3.3T  4.1T  45% /disk10
/dev/sdm        7.3T  3.4T  3.9T  47% /disk11
```

![image](https://user-images.githubusercontent.com/3234989/92699482-38a62f00-f380-11ea-9d0b-d89847d12a3f.png)

![image](https://user-images.githubusercontent.com/3234989/92699588-5d9aa200-f380-11ea-8a67-740a51631b6f.png)

![image](https://user-images.githubusercontent.com/3234989/92699818-a2bed400-f380-11ea-916a-8f4bc7bb9d0f.png)

![image](https://user-images.githubusercontent.com/3234989/92699946-c97d0a80-f380-11ea-96f0-c0c7dc2e689f.png)

![image](https://user-images.githubusercontent.com/3234989/92700142-0e08a600-f381-11ea-9afe-ba969e764ca9.png)

-----
![image](https://user-images.githubusercontent.com/3234989/92700456-68096b80-f381-11ea-8a2a-1381d17a337d.png)

I think I found the answer. . Why is the number of DPs of 228 the smallest after replacing a disk?

**Comment by zcola** [comment]
![image](https://user-images.githubusercontent.com/3234989/92701230-4fe61c00-f382-11ea-85b3-daa9ce533788.png)

I added 10 dp, and it still looks like 228 is the least

---

In fact, it is not a big problem. If the client can choose the fastest DP write

**Comment by awzhgw** [comment]
@zcola  the fast dp select writer has merge to master branch.
