### ISSUE TITLE
我应该采用哪种方式部署chubaofs，yum或者Kubernetes？

### ISSUE THREAD

**Issue by firezjs** [chubaofs/chubaofs#926]
当前想部署一套chubaofs供已有的Kubernetes环境使用，关于部署方式上有几个疑问还请帮忙解答下，谢谢。
1. 采用yum或者Kubernetes哪种部署方式是更为主流的部署方式？
2. 如果采用Kubernetes方式部署，是直接部署到当前有存储需求的Kubernetes环境中，还是独立搭建一套Kubernetes专门用于运行chubaofs。
3.  如果采用Kubernetes方式部署，其他的Kubernetes集群可以使用这套chubaofs吗？

**Comment by mervinkid** [comment]
1. 部署方式来说两种都可以。如果使用Kubernetes部署ChubaoFS，由于是基础存储，有一些注意事项：
- 确保IP、容器与物理机绑定
2. 主要看维护成本，分开部署的好处在于可以降低维护业务Kubernetes集群时误操作对存储的影响
3. 只要保证网络连通，确保使用ChubaoFS的业务容器可以直接与运行了DataNode、MetaNode、Master的容器直接通信即可。

**Comment by firezjs** [comment]
> 1. 部署方式来说两种都可以。如果使用Kubernetes部署ChubaoFS，由于是基础存储，有一些注意事项：
> 
> * 确保IP、容器与物理机绑定
> * 为Master、MetaNode、DataNode容器映射宿主机磁盘
> 
> 1. 主要看维护成本，分开部署的好处在于可以降低维护业务Kubernetes集群时误操作对存储的影响
> 2. 只要保证网络连通，确保使用ChubaoFS的业务容器可以直接与运行了DataNode、MetaNode、Master的容器直接通信即可。

**Comment by firezjs** [comment]
谢谢解答，如果用Kubernetes方式部署，对Kubernetes集群物理节点数有要求吗？比如最少要有几个worker节点？谢谢。

**Comment by chengyu-l** [comment]
@firezjs  ChubaoFS 在Kubernetes集群中部署和YUM在物理机部署的要求是相同的。ChubaoFS 建议Master & DataNode & MetaNode 几个组件部署在4个及以上节点（或物理机）。使用Helm部署ChubaoFS时，可以从集群中选择4个以上的节点，并为节点分别打标签（参见[ChubaoFS Helm文档](https://github.com/chubaofs/chubaofs-helm)）。在集群中选择哪些Node来部署ChubaoFS？建议使用大内存大磁盘空间的节点。MetaNode会占用较大的内存，DatNode需要大容量磁盘存储数据。在资源充足的情况下，建议将Master与DataNode & MetaNode部署在不同的节点上。

以上为集群资源较为充足，且计划将ChubaoFS作为生产环境使用的建议配置。

如果集群资源不足，或者仅仅是测试使用，使用Helm在Kubernetes集群中部署ChubaoFS Helm时，最少可以使用3个节点，在3个节点上同时部署Master & MetaNode & DataNode 这三个组件。在部署前，可以通过Helm 自定义value修改Master&DataNode&MetaNode这三个组件的默认配置参数，默认参数有哪些？可以参考[默认配置文件](https://github.com/chubaofs/chubaofs-helm/blob/master/chubaofs/values.yaml)，这些参数表示的含义，可以查看[ChubaoFS 的官方文档](https://chubaofs.readthedocs.io/zh_CN/latest/)

如果还有其他问题，欢迎咨询
