### ISSUE TITLE
 It is recommended to provide different priority IO for different storage volumes

### ISSUE THREAD

**Issue by awzhgw** [chubaofs/chubaofs#984]
In the actual production environment, a set of chubaofs can allocate a lot of storage volumes and use them for different storage services. Although these storage volumes are in different namespaces, the bottom layer is the same set of storage resources, but the business has priority.

Therefore, it is recommended that different businesses, on the datanode, have their IO priority sorted.

Cannot put the IO priority of mysql, es and the priority of database backup at the same level

**Comment by jadewang198510** [comment]
we can solve this problem by another way, e.g. use two different clusters
