### ISSUE TITLE
 It is recommended to optimize the sequential write replication protocol

### ISSUE THREAD

**Issue by awzhgw** [chubaofs/chubaofs#985]
The current primaryback replication protocol of chubaofs: the client first sends it to the first node of dp, and this node sends it to two follower nodes at the same time, then waits for a response, and finally returns to the client. It is recommended to add a new replication protocol option: the client sends directly to 3 datanodes, and after its application is successful, it is considered successful. This kind of replication protocol has the advantage that it can reduce the delay, which is helpful for some services that are particularly sensitive to delay, but it will cause the client's network card traffic to increase by 2 times

**Comment by awzhgw** [comment]
This kind of copy agreement is very good for operations that are all small files

**Comment by shuoranliu** [comment]
Glusterfs uses this kind of replication protocol that client sends data directly to 3 replicas. The main drawback of this protocol observed is that, from client point of view, only 1/3 of the network bandwidth can be seen. For example, fio sequential write test performance on glusterfs is 300MB/s in maximum, while the same test performance on other distributed file systems can reach up to 1GB/s, under identical hardware conditions.

**Comment by awzhgw** [comment]
@shuoranliu  
This can be made into a configuration option, which is very useful in some situations, such as a large number of small file scenarios, or ES, or mysql scenarios. .

**Comment by shuoranliu** [comment]
It's not just the throughput, but iops also has hardware limit and the client can only see 1/3 of the hardware ability.
